### ISSUE TITLE
QQ Music not scrobbling

### ISSUE THREAD

**Issue by arianasenky** [web-scrobbler/web-scrobbler#4468] opened 2024-01-28 21:12 UTC
**Describe the bug**
QQ Music not scrobbling. y.qq.com

**How to reproduce**
1. Go to 'y.qq.com'
2. Click on 'play'
3. not scrobbling

**Expected behavior**
please fix it

**Screenshots**
![screenshot-1706475954244](https://github.com/web-scrobbler/web-scrobbler/assets/157824870/2a3e7cc7-3505-4e45-baf4-b385359eabbe)

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: Window 10
-   Browser: Edge
-   Extension version: v.3.5.0

**Comment by yayuyokitano** [comment] 2024-01-28 21:18
Duplicate of #3498 
Patch is coming next update

**Closed by yayuyokitano** 2024-01-28 21:18 UTC
Labels: bug
