### ISSUE TITLE
LiveXLive changed its name to LiveOne

### ISSUE THREAD

**Issue by thomwim** [web-scrobbler/web-scrobbler#3130] opened 2022-02-15 06:20 UTC
The LiveXLive connector (livexlive.com) should be changed to LiveOne, because the website changed its name.

https://www.liveone.com

**Comment by inverse** [comment] 2022-02-16 21:25
Duplicate of #3126 which was fixed in the latest release

**Closed by inverse** 2022-02-16 21:25 UTC
Labels: connector, request
