### ISSUE TITLE
music.youtube support

### ISSUE THREAD

**Issue by blittzzo** [web-scrobbler/web-scrobbler#1675] opened 2018-07-18 22:15 UTC
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

**Comment by pschfr** [comment] 2018-08-05 01:07
Duplicate of #1674

**Closed** 2018-09-12 07:45 UTC
Labels: connector, request
