### ISSUE TITLE
Function for manual tracklist uploading

### ISSUE THREAD

**Issue by killd0zr** [web-scrobbler/web-scrobbler#2029] opened 2019-07-30 08:57 UTC
Hello, is there any way to upload and scrobble the whole tracklist **manually**? Tracklists are usually made for mixes or concerts on YouTube and can be found in description

Type of tracklist for example:

00:00 Sublab x Azaleh - You Found Me
05:00 Sloati - My Sorrow
09:35 Kazukii x Meseta - Nukira
13:13 alivvve - Change

**Comment by killd0zr** [comment] 2019-07-30 08:58
Before automatic description scrobbling feauture is implemented, manual tracklistuploading function could be very useful for many users

**Comment by alexesprit** [comment] 2019-07-30 09:06
Do you think manual uploading is easier to implement? The hardest part is to write a parser of different types of playlists. This code is common for automatic and manual scrobbling. I've already written the initial implementation of automatic scrobbling of tracklists, but the parser is not complete. Plus, we have no mechanisms for manual scrobbling/uploading, so we should also write new code, that will be replaced with existing code in future.

So, I doubt the sense of this issue, because, technically, it's still a dupe of #122.

**Comment by killd0zr** [comment] 2019-07-30 09:09
There

> Do you think manual uploading is easier to implement? The hardest part is to write a parser of different types of playlists. This code is common for automatic and manual scrobbling. I've already written the initial implementation of automatic scrobbling of tracklists, but the parser is not complete. Plus, we have no mechanisms for manual scrobbling/uploading, so we should also write new code, that will be replaced with existing code in future (and this is waste of time).
> 
> So, I doubt the sense of this issue, because, technically, it's still a dupe of #122.

https://github.com/nkbt/scrobbler
There are some bulk scrobblers on GitHub, their developments can be used

**Comment by alexesprit** [comment] 2019-07-30 09:14
I'm talking not about this feature, but about its useless, because we should write **more** code for manual scrobbling.

**Comment by marsjaninzmarsa** [comment] 2019-07-30 16:22
> There are some bulk scrobblers on GitHub, their developments can be used for this feature

Software development does not work that way. We have scrobbling feature (the main feature of this plugin, heh), the missing piece is the interface capable of handling more than one song simultaneously and none of their developments could help with that.

**Comment by jaccarmac** [comment] 2019-07-30 23:12
I would add that there are other excellent *manual* scrobblers out there, such as elamperti/openwebscrobbler. Sometimes you just need to use multiple tools to capture all your listening for use on Last.fm, and something like full manual operation seems somewhat out of scope for this plugin.

(At least for my usecase, which is mostly letting it pick up my listens in the background :) )

**Closed** 2019-10-20 12:08 UTC
Labels: won't fix

**Comment by alexesprit** [comment] 2019-10-20 12:10
Base description parser is implemented here: https://github.com/web-scrobbler/web-scrobbler/commits/feature/yt-description, so it's better to contribute to this branch by adding support for different tracklist formats.
