### ISSUE TITLE
Add per-website URL pattern blacklist

### ISSUE THREAD

**Issue by fishstik** [web-scrobbler/web-scrobbler#2557] opened 2020-09-14 15:41 UTC
**Is your feature request related to a problem? Please describe.**
I want to disable scrobbling only for certain YouTube channels. I will frequently forget to skip the track or disable the connector and non-music scrobbles will appear in Last.fm.

**Describe the solution you'd like**
In addition to the URL patterns feature that already exists, add a URL-pattern blacklist, so that URL patterns can be defined that will prevent scrobbling.

**Describe alternatives you've considered**
I do not want to use the `Scrobble videos from "Music/Entertainment" category` option because there are other channels I would like to scrobble as well. It makes sense to implement this feature in this way since the URL pattern matching feature already exists. Open to other alternatives.

**Additional context**
To solve my problem (always skip certain YouTube channels), a userscript that adds the YouTube channel ID to the URL is required (I am using [this one](https://greasyfork.org/en/scripts/392590-whitelist-youtube-channels-ads)). I am also using this script to whitelist certain channels for uBlock Origin.

**Comment by alexesprit** [comment] 2020-09-14 18:19
Duplicate of #2557.

**Closed** 2020-09-14 18:20 UTC
Labels: feature
