### ISSUE TITLE
Scrobbler Doesn't See Amazon Alexa "Now Playing" Page Until Chrome Refresh

### ISSUE THREAD

**Issue by mainadungo** [web-scrobbler/web-scrobbler#1360] opened 2017-07-21 18:12 UTC
I use this scrobbler so that Last.FM sees Spotify music played directly from Alexa (as opposed to being started from my phone or PC), since their is no native functionality for this yet.

On my server, I have Chrome start with Windows, and have the "Now Playing" page (http://alexa.amazon.com/spa/index.html#player) set as my homepage. When Chrome starts, the scrobbler extension is grayed out, and won't see the music until I hit refresh. Then it all works as expected. It also works as expected with no need for a refresh if I launch the "Now Playing" page manually rather than launching as my home page.

Has anybody seen anything like this, and/or have any ideas on how to get around it? This method is so close to being a solution for Alexa scobbling.

I'm thinking about setting up an AHK to refresh Chrome a single time at X amount of seconds after Chrome launch, but that's silly workaround pasted on top of a silly workaround. There has to be a better option.

Side note- every browser refresh creates a duplicate scrobble. Is that expected/known behavior?

**Comment by alexesprit** [comment] 2017-07-23 05:57
@mainadungo I cannot reproduce this issue on latest Chrome Canary. Can you try to reproduce in on Canary?

Can you also provide the extension logs? [How to debug extensions.](https://github.com/david-sabata/web-scrobbler/wiki/How-to-debug-the-extension)

Here are the steps to get the proper logs:
1. Start your browser.
2. Collect the logs after page is loaded.
3. Refresh the tab with Alexa page.
4. Collect the logs again and paste them it this thread using any pastebin service.

> Side note- every browser refresh creates a duplicate scrobble. Is that expected/known behavior?

No, it's not expected and is not known behaviour.

**Comment by mainadungo** [comment] 2017-07-24 18:56
Yep, reproducible on Canary. Same exact behavior. I'll send logs ASAP.

The browser refresh (F5) issue does NOT occur in Canary, and doesn't even occur in regular Chrome all the time. Seems intermittent. Also, I've seen the duplicate scrobbles while a song is playing ("a minute ago" and "scrobbling now"), but it clears itself out once the song is done. So maybe a non-issue?

**Comment by mainadungo** [comment] 2017-07-24 19:49
Got the refresh issue to show itself. This was after several F5s in Chrome and Canary.
![image](https://user-images.githubusercontent.com/22915475/28541610-436dfd6e-707f-11e7-978f-9ce2ec0c921a.png)

**Comment by mainadungo** [comment] 2017-07-24 19:57
Okay, here are the post-refresh logs. 
https://gist.github.com/mainadungo/a85cf87dc85568aab68e2b90d4e12fe0

Interesting problem- if I already have another instance of Chrome running, such as the Developer Tools where the logs are kept, the issue does not occur. So I can't capture logs of the actual issue.

**Comment by alexesprit** [comment] 2017-07-25 04:22
> Okay, here are the post-refresh logs.

I see no issues in this logs.

Is is also happening with other websites or just with Alexa page?

I didn't reproduce "refresh" issue. I don't understand totally what are you talking about, but I've tried to reproduce it by a following way:
1. Open some music website (I used Spotify) and play some song (1).
2. Refresh the tab and play another song (2).

The extension doesn't scrobble song (1), as it's expected. Am I correct?

**Comment by mainadungo** [comment] 2017-07-25 19:04
Sorry I wasn't more clear- when I hit refresh, it scrobbles the same song over and over again, as if I listened to it twice. (See Iron Maiden screenshot above.)

Very interesting... the original bug only seems to occur on the Alexa "Now Playing" page. If I set my homepage to Spotify or Youtube, it functions completely as expected and desired.

**Comment by mainadungo** [comment] 2017-07-27 15:46
Update- I'd love to hear the future status of these two issues whenever updates become available, but for now I think I'm set. 

I'm using Super Auto Refresh Chrome extension, set to 3 minutes, and that takes care of the issue where the scobbler doesn't see the Alexa "Now Playing page". 3 minutes also seems like a slow enough  refresh to not cause the refresh issue (Iron Maiden) yet. I'll report back if that ends up not being the case.

**Comment by alexesprit** [comment] 2017-07-29 09:37
@mainadungo I still can't reproduce the issue. Btw, I have no Alexa device (but I can open the player page, though); don't know if it matters.

What operating system do you use? I'm on Windows 10.

Please also make sure you're not redirected to another page.

I'm still waiting for logs after first browser start (when the extension doesn't see the Alexa page).

**Comment by alexesprit** [comment] 2017-07-30 07:42
Reproduced on Kubuntu.

**Comment by alexesprit** [comment] 2017-07-30 09:35
I'm not sure if this issue is on the extension side. I tried debugging the extension and found out the `chrome.tabs.onUpdated` event is not fired for tabs opened on Chrome startup. This is true for Linux (I reproduced the issue on Kubuntu running on VirtualBox). I have no issue while using the extension on Windows 10. I also tried to add a random URL supported by web scrobbler as a homepage; the story is the same.

**Comment by alexesprit** [comment] 2017-07-30 10:18
https://bugs.chromium.org/p/chromium/issues/detail?id=750487

**Comment by mainadungo** [comment] 2017-07-31 15:11
Nice job, thanks a lot for sticking with this. Very interesting findings. I'm on Win7x64.

**Comment by alexesprit** [comment] 2019-05-04 13:03
I close this one because it cannot be fixed on the extension side. Probably, it was resolved already.

**Closed by alexesprit** 2019-05-04 13:03 UTC
Labels: bug, connector
