### ISSUE TITLE
Scrobble text filters

### ISSUE THREAD

**Issue by jdznd** [web-scrobbler/web-scrobbler#2495] opened 2020-07-29 23:41 UTC
I'd been scrobbling only from local sources for many years but recently I discovered this wonderful extension and started to scrobble from various websites. Which expanded my music listening significantly.

My only nitpicking is that I often have to 'clean' text manually. I want to scrobble with original song/album as possible.

https://music.youtube.com/playlist?list=OLAK5uy_mTxMeNCXzTJ7o7ifHrGsaLOd6Jq_pIyqY
For example, I want to listen to this album but there are so many 'dirty' part on the text such as "2003 remaster", "deluxe edition". I really need a fine solution to remove them automatically.

Regular expression support would be perfect but simply removing (*), [*] brackets that contains certain keywords (which can be configured by users) would be enough for me.

**Comment by alexesprit** [comment] 2020-07-30 04:31
Closed as a duplicate of #1552.

**Closed** 2020-07-30 04:34 UTC
Labels: feature
