### ISSUE TITLE
[not working, need help] Ability to scrobble tracks from music mixes on YouTube 

### ISSUE THREAD

**Issue by killd0zr** [web-scrobbler/web-scrobbler#2022] opened 2019-07-26 00:42 UTC
I found that feature I was requesting for is already implemented, but it doesnt work here. I got shown and scrobbled only main videoclip title, not tracks inside it.

```
> I like to listen genre mixes on YouTube, mixes are 1-2 hrs videoclips, consisting of 20-30 songs of specific genre. Usually author puts tracklist with time stamps and track names in the description of the video. But when scrobbling such mix,  the whole thing counts as a one single track, and there is no way for manually upload tracks Unability to scrobble tracklists brings sad experience to mix listeners.
> 
> Current manual solution:
> 1. Manually scrobble tracks from tracklist one by one, by using third party services
> 2. Convert tracklist to CSV and format all fields, then import and scrobble by using third party services
> 
> Doing this routine process after each mix is very difficult for typical users, so all we have 
> 
> Possible options of solving:
> 1. New button for uploading tracklist, which appears if clip length is too big for single track (20-30mins and more). Pressing a button opens a window for user to paste the tracklist. New problem is that each author uses his own style of formatting tracklist (see attached picture), so here we need advanced parsing algorythm.
> 2. Button for bulk scrobbling, it stays active all the time, it opens a window and accepting texts, but user should format tracklist by himself according by format rules. (f.e. by making "Artist -Title" on each string and removing other data)
> 3. Button with feature of automatic searching of tracklist by parsing HTML code of the page
> 
> Community would be very grateful for fixing and bringing ability to scrobble this type of music content. Looking forward to discuss this, it would be pleasure for me to help.
> ![2019-07-26_05-07-26](https://user-images.githubusercontent.com/53320300/61917754-27c21080-af68-11e9-9328-10d4b1bf16c6.png)
> 
```

**Comment by killd0zr** [comment] 2019-07-26 01:44
Checked other issues and found that this feature already had been implemented. 
Do I need to do anything to activate it? On my side tracks from mix are not scrobbled. Only mix name is being scrobbled (as on picture)

**Comment by killd0zr** [comment] 2019-07-26 02:51
Tried to reinstall app, tried to check "force recognition"
Tried several mixes with different types of tracklist format, still not recognizing tracks inside mix

**Comment by alexesprit** [comment] 2019-07-26 04:02
Looks like it's a dupe of #122. This is not implemented.

**Closed by alexesprit** 2019-07-26 04:02 UTC
Labels: feature
