### ISSUE TITLE
Not scrobbling from Bandcamp

### ISSUE THREAD

**Issue by catte-ish** [web-scrobbler/web-scrobbler#2584] opened 2020-10-06 13:56 UTC
I am playing music on bandcamp and unlike as usual, when the web scrobbler picks up the data and the icon is shown as a tick, the icon just remains a magnifying glass and will not pick up any song from the album. As a result no songs that I stream are scrobbled to my last.fm profile.

-   OS: Mac
-   Browser: Chrome, Safari
-   Extension version: 2.36.0
-   Service: Last.fm

**Comment by alexesprit** [comment] 2020-10-06 14:00
Could you provide debug logs? [How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by alexesprit** [comment] 2020-10-06 14:01
Duplicate of #2583.

**Closed by alexesprit** 2020-10-06 14:01 UTC
Labels: bug

**Comment by qvp1** [comment] 2020-10-06 15:58
Im having a similar problem. 
 
heres a copy of the debug log:

Tab 3970: New song detected: {
  "track": null,
  "artist": null,
  "album": "Scale",
  "albumArtist": null,
  "uniqueID": null,
  "duration": 224,
  "currentTime": null,
  "isPlaying": true,
  "trackArt": "https://f4.bcbits.com/img/a2319201197_16.jpg",
  "isPodcast": false,
  "originUrl": "https://matthewherbert.bandcamp.com/album/scale"
}
saved-edits.model.js:169 Uncaught (in promise) Error: Empty song
    at Function.makeSongId (saved-edits.model.js:169)
    at SavedEditsImpl.loadSongInfo (saved-edits.model.js:31)
    at async Object.process (user-input.js:16)
    at async Pipeline.process (pipeline.js:25)
    at async Controller.processSong (controller.js:338)
