### ISSUE TITLE
After enabling "scrobble Music/Entertainment categories only" Scrobble stops working (Chrome). Disabling categories helps, but I don't wan't to scrobble podcasts, cookie shows and other unrelated stuff. Any help? 

### ISSUE THREAD

**Issue by Rushwheel** [web-scrobbler/web-scrobbler#1930] opened 2019-03-04 19:53 UTC
### Steps to reproduce (for bugs)

1\.
2\.
3\.

### Steps for resolving the issue

-   [ ] Reauthenticate on Last.fm
    
    
    
-   [ ] Try to use unpacked extension from latest master
    
    
-   [ ] Check other issues for duplicates

### Environment

-   Version used:
-   Browser name and version:

**Comment by inverse** [comment] 2019-03-05 17:42
Dupe of #1897

**Closed by inverse** 2019-03-05 17:42 UTC
