### ISSUE TITLE
Exclusion pattern

### ISSUE THREAD

**Issue by seongbin** [web-scrobbler/web-scrobbler#2794] opened 2021-03-26 08:31 UTC
**Is your feature request related to a problem? Please describe.**
> Personally I am scrobbling spotify tracks into last.fm, and for those tracks with multi artist separate artists with comma blank(, ) which last.fm cannot recognize. I would rather ignore these scrobbles.

**Describe the solution you'd like**
> Is it possible to make an option like custom regexp or delimiter selection to make exceptions.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

**Additional context**
_Add any other context or screenshots about the feature request here._
![screenshot](https://user-images.githubusercontent.com/1720769/112603982-af1df200-8de3-11eb-8d35-dbca1a3890e7.png)

**Comment by alexesprit** [comment] 2021-03-26 08:39
I guess it's a duplicate of #2588.

**Closed by alexesprit** 2021-03-26 08:39 UTC
Labels: feature
