### ISSUE TITLE
WS including "- Topic" in artist field on YouTube

### ISSUE THREAD

**Issue by 06000208** [web-scrobbler/web-scrobbler#4044] opened 2023-08-21 15:42 UTC
**Describe the bug**
First noticed this happening about a week ago. Web scrobbler is including the "- Topic" in the artist field, meaning it's taking text from the channel's title rather than metadata or the description.

Additionally, it appears youtube has stopped showing some music related metadata on some topic channels, even when it is clearly aware of the song:

[potsu - letting go](https://www.youtube.com/watch?v=WqCpWu8tgRw), showing metadata | [Toby Fox - Field of Hopes and Dreams](https://www.youtube.com/watch?v=ymNgfwgh1TU), without metadata
:-------------------------:|:-------------------------:
![potsu - letting go](https://github.com/web-scrobbler/web-scrobbler/assets/52764066/ed82a843-302e-43c6-a83a-b8acfcfe3d18) | ![Toby Fox - Field of Hopes and Dreams](https://github.com/web-scrobbler/web-scrobbler/assets/52764066/1dd05954-532a-4fd4-a36a-ae410c6ed4e7)

When youtube stopped showing those fields as consistently, or whether or not web scrobbler uses them, I don't know. However, I do know that web scrobbler used to scrobble these videos correctly, because on the song [Abstract Orchestra - ALL CAPS](https://www.youtube.com/watch?v=QlGGqUBYKzI), which I know is the same video I listened to before, I have 6 old scrobbles with the correct metadata, and 1 scrobble from after the issue started:

Before | After
:-------------------------:|:-------------------------:
![Before](https://github.com/web-scrobbler/web-scrobbler/assets/52764066/04f0ab26-3841-4dfc-9a45-684945a455d8) | ![After](https://github.com/web-scrobbler/web-scrobbler/assets/52764066/db25311c-34f6-4103-ba5a-4a9ddef2dc7e)

**How to reproduce**
1. Go to https://www.youtube.com/watch?v=QlGGqUBYKzI
2. Begin playing the song with extension enabled
3. Note that WS has taken the artist name from the channel's name, the song being attributed to "Abstract Orchestra - Topic" rather than "Abstract Orchestra"

**Debug logs**
https://paste.gg/p/anonymous/f519ff46bda54ff5a2cfd727c33bcc98

**Environment**
- OS: Windows 11
- Browser: Firefox 116.0.3 (64-bit
- Extension version: v3.0.15

**Comment by yayuyokitano** [comment] 2023-09-08 20:50
Odd, I'm still not able to repro on those specific songs either.
Maybe there's some sort of gradual rollout going on?

Could you try running the following two commands on one of the songs that aren't working and see what you get in return?
`document.querySelector("#meta-contents #description").innerText`
`document.querySelector(".crawler-full-description").innerText`

**Comment by 06000208** [comment] 2023-09-11 09:50
On [Abstract Orchestra - ALL CAPS](https://www.youtube.com/watch?v=QlGGqUBYKzI)
```
04:48:04.109 document.querySelector("#meta-contents #description").innerText
04:48:04.164 Uncaught TypeError: document.querySelector(...) is null
    <anonymous> debugger eval code:1
debugger eval code:1:10
```
```
04:48:15.823 document.querySelector(".crawler-full-description").innerText
04:48:15.882 Uncaught TypeError: document.querySelector(...) is null
    <anonymous> debugger eval code:1
debugger eval code:1:10
```

**Comment by yayuyokitano** [comment] 2023-09-11 10:04
Odd. meta-contents should be hidden, but it's not normally empty.
Guess it's a partial rollout thing.
What does `document.querySelector("#content #description").innerText` yield?
The issue on potsu - letting go is an unrelated one, and a duplicate of #2742 my apologies for not catching that earlier. For that one, we simply have not implemented support for those fields yet.

**Comment by 06000208** [comment] 2023-09-11 18:13
```
13:12:55.804 document.querySelector("#content #description").innerText
13:12:55.860 "214,532 views  Nov 1, 2018
Provided to YouTube by KudosRecords

ALL CAPS · Abstract Orchestra

Madvillain, Vol. 1

℗ ATA Records Ltd.

Released on: 2018-11-02

Main  Artist: Abstract Orchestra
Music  Publisher: Copyright Control
Composer: Daniel Dumile Jackson
Composer: Otis Thompson
Composer: Daniel Clifford Thompson
Composer: Madlib

Auto-generated by YouTube.
Shorts remixing this video
Does Game Runners have Wii U games?
32K views
me, myself, and I #abstractart #abstractpainting #artprocessvideo
1.7K views
#pokemon #freecodefriday
1.1K views
chiken z
861 views
Dylon - The Cycle: Frontiers - #shorts
133 views
Abstract Orchestra - Topic
2.95K subscribers
Videos
About
Show less"
```

**Comment by yayuyokitano** [comment] 2023-09-11 21:32
Odd. I'll have to investigate more, our youtube pages are not at all consistent.

**Comment by 06000208** [comment] 2023-09-14 21:46
> I've also had this stupid issue intermittently

If you've also had this issue, does the regex edit I [posted above](https://github.com/web-scrobbler/web-scrobbler/issues/4044#issuecomment-1686592815) work for you?

**Comment by 06000208** [comment] 2024-01-28 21:38
As mentioned here https://github.com/web-scrobbler/web-scrobbler/issues/4240#issuecomment-1893222898, the conclusion I drew in the OP that web scrobbler was taking the artist from the channel's username is correct, meaning this issue also affects music channels whose usernames are slightly different or something else entirely. For example, The Shins' channel name is theshins without the space, and They Might Be Giants' is ParticleMen, referencing one of their songs.

**Closed** 2024-01-31 22:01 UTC
Labels: bug
