### ISSUE TITLE
Request to add Stream Elements' Media Request to "Supported Websites"

### ISSUE THREAD

**Issue by aquinox77** [web-scrobbler/web-scrobbler#2884] opened 2021-05-31 05:30 UTC
I use this to play media on stream, and would really appreciate it if I could scrobble the music I play from this site:

https://streamelements.com/dashboard/mediarequest/general

Cheers! <3

**Comment by alexesprit** [comment] 2021-05-31 08:47
Looks like it's a duplicate of #2527.

By the way, I still don't understand what is this, and how we should add support for this. Have you any examples?

**Comment by alexesprit** [comment] 2021-06-05 11:11
Close as a duplicate of #2527.

**Closed by alexesprit** 2021-06-05 11:11 UTC
Labels: feature
