### ISSUE TITLE
last.fm suggested corrections problem (repeat problem)

### ISSUE THREAD

**Issue by ksshea** [web-scrobbler/web-scrobbler#3945] opened 2023-07-05 13:14 UTC
**Describe the bug**

A repeat of issue https://github.com/web-scrobbler/web-scrobbler/issues/1921 that I raised a few years ago just resurfaced.

To repeat what is in that ticket:

1. play https://open.spotify.com/track/1WiRiK9gFuFhx1JVyEclo8?si=32a3411465854043 on spotify (Lay My Love by Yukihiro Takahashi)
2. Check the Web Scrobbler "now playing"
3. see the scrobble details as extracted by Spotify (see first screenshot)
4. check last.fm and last.fm's suggested correction is playing (see second screenshot)

Note: the actual scrobble count for that particular track is 15, so the last.fm suggestions get in the way of count retrieval

**Expected behavior**

Web scrobbler should:
1. replace Spotify's text with last.fm's as a suggestion (optional)
2. submit any subsequent user edits to the track as given

**Screenshots**

![image](https://github.com/web-scrobbler/web-scrobbler/assets/89649565/1443dd74-924b-4f64-987d-aef9b1c2e941)

![image](https://github.com/web-scrobbler/web-scrobbler/assets/89649565/995c474d-4734-47f9-bce6-91a7d3d8f0b7)

**Debug logs**

main.js:5 changed mode to Loading in tab 1696119645
main.js:1 Web Scrobbler: Unable to bind Libre.fm
R @ main.js:1
bindAllScrobblers @ main.js:5
await in bindAllScrobblers (async)
Wt @ main.js:5
fn @ main.js:5
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 ListenBrainz: no data
_ @ main.js:1
debugLog @ main.js:3
getSession @ main.js:5
await in getSession (async)
bindAllScrobblers @ main.js:5
await in bindAllScrobblers (async)
Wt @ main.js:5
fn @ main.js:5
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 Error: Could not establish connection. Receiving end does not exist.
    at ge (main.js:1:9102)
(anonymous) @ main.js:1
Promise.catch (async)
gt @ main.js:1
le @ main.js:1
await in le (async)
ys @ main.js:5
await in ys (async)
Vt @ main.js:5
fn @ main.js:5
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 No data in storage
_ @ main.js:1
signOut @ main.js:3
await in signOut (async)
signOut @ main.js:5
getSession @ main.js:5
await in getSession (async)
bindAllScrobblers @ main.js:5
await in bindAllScrobblers (async)
Wt @ main.js:5
fn @ main.js:5
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 Web Scrobbler: Unable to bind ListenBrainz
R @ main.js:1
bindAllScrobblers @ main.js:5
await in bindAllScrobblers (async)
Wt @ main.js:5
fn @ main.js:5
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 Web Scrobbler: Unable to bind Maloja
R @ main.js:1
bindAllScrobblers @ main.js:5
await in bindAllScrobblers (async)
Wt @ main.js:5
fn @ main.js:5
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 Web Scrobbler: Send "get info" request: 1
main.js:1 Last.fm: track.getinfo response:
{
  "track": {
    "name": "Yukihiro Takahashi",
    "url": "https://www.last.fm/music/lay+my+love/_/Yukihiro+Takahashi",
    "duration": "0",
    "streamable": {
      "#text": "0",
      "fulltrack": "0"
    },
    "listeners": "1",
    "playcount": "1",
    "artist": {
      "name": "lay my love",
      "url": "https://www.last.fm/music/lay+my+love"
    },
    "userplaycount": "0",
    "userloved": "0",
    "toptags": {
      "tag": []
    }
  }
}
main.js:5 song changed in tab 1696119645
main.js:5 {parsed: {…}, noRegex: {…}, processed: {…}, metadata: {…}, flags: {…}, …}
main.js:1 Web Scrobbler: Unable to bind Libre.fm
R @ main.js:1
bindAllScrobblers @ main.js:5
await in bindAllScrobblers (async)
$t @ main.js:5
fn @ main.js:5
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 ListenBrainz: no data
_ @ main.js:1
debugLog @ main.js:3
getSession @ main.js:5
await in getSession (async)
bindAllScrobblers @ main.js:5
await in bindAllScrobblers (async)
$t @ main.js:5
fn @ main.js:5
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 No data in storage
_ @ main.js:1
signOut @ main.js:3
await in signOut (async)
signOut @ main.js:5
getSession @ main.js:5
await in getSession (async)
bindAllScrobblers @ main.js:5
await in bindAllScrobblers (async)
$t @ main.js:5
fn @ main.js:5
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 Web Scrobbler: Unable to bind ListenBrainz
R @ main.js:1
bindAllScrobblers @ main.js:5
await in bindAllScrobblers (async)
$t @ main.js:5
fn @ main.js:5
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 Web Scrobbler: Unable to bind Maloja
R @ main.js:1
bindAllScrobblers @ main.js:5
await in bindAllScrobblers (async)
$t @ main.js:5
fn @ main.js:5
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 Web Scrobbler: Send "now playing" request: 1
main.js:1 Error: Could not establish connection. Receiving end does not exist.
    at ge (main.js:1:9102)
(anonymous) @ main.js:1
Promise.catch (async)
gt @ main.js:1
le @ main.js:1
await in le (async)
ys @ main.js:5
await in ys (async)
Zt @ main.js:5
fn @ main.js:5
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:1 Last.fm: track.updatenowplaying response:
{
  "nowplaying": {
    "artist": {
      "corrected": "0",
      "#text": "Lay My Love"
    },
    "track": {
      "corrected": "0",
      "#text": "Yukihiro Takahashi"
    },
    "ignoredMessage": {
      "code": "0",
      "#text": ""
    },
    "albumArtist": {
      "corrected": "0",
      "#text": ""
    },
    "album": {
      "corrected": "0",
      "#text": "Blue Moon Blue"
    }
  }
}
main.js:5 changed mode to Playing in tab 1696119645
main.js:1 Error: Could not establish connection. Receiving end does not exist.
    at ge (main.js:1:9102)
(anonymous) @ main.js:1
Promise.catch (async)
gt @ main.js:1
le @ main.js:1
await in le (async)
ys @ main.js:5
await in ys (async)
Vt @ main.js:5
fn @ main.js:5
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 3.0.15

**Additional context**

While last.fm's suggestions may be "correct" and appropriate in a global sense, they're not useful in a personal sense for someone who doesn't read Japanese or have a kanji-capable input device

**Comment by jaccarmac** [comment] 2023-07-06 15:54
This is a redirect on Last.fm's side. See https://www.last.fm/music/Yukihiro+Takahashi: It's necessary to add `+noredirect` to the URL as suggested to get to the Latin version of the page.

Such edits can happen for artists, albums, and songs. Occasionally it's inconsistent or annoying. However, I'm not sure if there's any way to force the scrobble. For example [Drip Dry Eyes](https://www.last.fm/music/%E9%AB%98%E6%A9%8B%E5%B9%B8%E5%AE%8F/_/Drip+Dry+Eyes) and its [noredirect variant](https://www.last.fm/music/+noredirect/Yukihiro+Takahashi/_/Drip+Dry+Eyes) have identical playcounts.

**Comment by yayuyokitano** [comment] 2023-07-20 09:01
Sorry for late response, been busy irl and only getting around to issues now.

Looked into this in some more detail, the Lastfm api/website is bugging here, there might have been an update from their end that made the issue worse than previously.
When I reproduced this, the results not only indicate that we are sending the right info, lastfm is insisting it is not even applying any correction to the artist name!
Scrobbles will still scrobble with english names as long as you have noredirect enabled as described above, though now playing seems to stay broken regardless, and I don't see a way to solve it.

Keep in mind that you still need to edit the track once to get the english title scrobbling, just like it worked previously.

Overall, whatever is happening here seems to be on lastfm, not us, so I'm closing the issue until further notice.

**Closed as not planned by yayuyokitano** 2023-07-20 09:01 UTC
Labels: bug

**Comment by yayuyokitano** [comment] 2023-07-20 09:03
Oh and to add, make sure you have "Auto-correct the spelling of your scrobbles" disabled in your website settings in lastfm.
This still does not fix now playing though.

**Comment by ksshea** [comment] 2023-07-21 20:49
Thanks for the update.

Auto correct has always been off on last.fm.  I'll have a look at this myself at some point
