### ISSUE TITLE
Polish Programmer's Keyboard Layout and 'ł' character key combination (Alt Gr + L) does not work with the extension on

### ISSUE THREAD

**Issue by permutoatalfafinance** [web-scrobbler/web-scrobbler#2002] opened 2019-06-25 13:30 UTC
**Describe the bug**
Cannot put polish 'ł' character in Chrome using "polish programmer's keyboard" on MacOs when Web Scrobbler extension is active.

*How to reproduce**
1. Go to address bar or any text input on any website (Make sure you have polish programmer's keyboard layout set in the system)
2. Try to put 'ł' character using polish programmer's keyboard (Alt Gr + L)
3. Nothing happens

**Expected behavior**
The 'ł' character is put to the input field.

**Environment (please complete the following information)**
-   OS: Mac
-   Browser: Chrome
-   Extension version: (e.g. v2.20.2)

**Additional context**
It is observed only on my browser, every other place in the system polish programmers keyboard layout works fine with 'ł' character. Also could not find any shortcut settings for web scrobbler extension. I though it might have been some shortcut that overrides the keyboard. I assume it it this extension because when I turn it off 'ł' character works as normal.

**Comment by alexesprit** [comment] 2019-06-25 13:36
Hi! It's a sort of duplicate of #1999.

The solution is described in natch potes: https://github.com/web-scrobbler/web-scrobbler/releases/tag/v2.20.3.

**Closed by alexesprit** 2019-06-25 13:36 UTC
Labels: bug

**Comment by inverse** [comment] 2019-06-25 19:19
Off-topic I had a similar thing happen to me with this extension: https://github.com/berrberr/streamkeys - It gobally bound to my media keys recently preventing gnome being able to control my usual media apps

**Comment by wychowanek** [comment] 2019-07-16 10:05
I am trying to open `chrome://settings/keyboardShortcuts` page on macOS but it just sends me to Chrome settings so it still is an issue for me. I have checked and I do have 2.20.3 version installed
