### ISSUE TITLE
Last.fm not scrobbling from Spotify

### ISSUE THREAD

**Issue by ktvsky** [web-scrobbler/web-scrobbler#3112] opened 2022-01-27 16:27 UTC
Last.fm not scrobbling from Spotify (Google Chrome Browser)

Steps:
1. Go to 'open.spotify.com'
2. Click on any track to play
3. Check the scrobbler extension

actual behavior: scrobbling is not working
Expected behavior: scrobbling is working
![11111111](https://user-images.githubusercontent.com/98543871/151401562-4d196677-1bf2-44f7-a8b8-b7da60b0783c.png)

**Comment by inverse** [comment] 2022-01-27 22:05
Duplicate of #3105

**Closed by inverse** 2022-01-27 22:05 UTC
Labels: bug
