### ISSUE TITLE
SiriusXM Scrobbling Issue

### ISSUE THREAD

**Issue by andysmiley** [web-scrobbler/web-scrobbler#3869] opened 2023-06-06 14:54 UTC
**Describe the bug**
SiriusXM player has scrobbling issues with Web Scrobbler in Microsoft Edge. It scrobbles any player info that has album cover art. Any songs that don't have cover art showing in the player (just like info during station sweepers and DJ breaks) doesn't scrobble at all. Before the update, Web Scrobbler would scrobble everything (including DJ break info).

**Environment (please complete the following information)**
-   OS: Windows 11
-   Browser: Microsoft Edge
-   Extension version: v3.0.10

**Comment by inverse** [comment] 2023-06-06 20:37
Dupe of #3769 - will be fixed in the next release

**Closed by inverse** 2023-06-06 20:37 UTC
Labels: bug
