### ISSUE TITLE
New text under youtube's videos titles, how to remove?

### ISSUE THREAD

**Issue by cajeni2050** [web-scrobbler/web-scrobbler#4361] opened 2023-12-14 14:56 UTC
I have noticed that now under the title of any video I watch on youtube I get a webscrobbler icon with a message saying "Scrobbling is not allowed. Click web scrobbler extension icon for more information." Is this new behaviour and is it possible to hide this message?

**Comment by wolveix** [comment] 2023-12-14 15:42
Looks like a duplicate of #4355 :)

**Closed** 2023-12-14 15:45 UTC
Labels: question
