### ISSUE TITLE
Options button crashes browser

### ISSUE THREAD

**Issue by Ser-Erate** [web-scrobbler/web-scrobbler#3788] opened 2023-05-27 22:53 UTC
**Describe the bug**
When clicking the options button on Web Scrobbler, it immediately crashes my browser (Vivaldi Browser, I'm unsure if the same happens on other browsers), and upon reopening it Web Scrobbler seems somewhat broken for a while; It can still scrobble, but it does not display as scrobbling (simply says "This website is not supported", on YouTube, YouTube Music, and Bandcamp, I haven't checked others), and it seems impossible to edit tracks. Reinstalling the extension fixed the problem, and waiting a few minutes to have fixed it as well, however neither restarting the browser nor my computer were effective.

**How to reproduce**
1. Open Vivaldi Browser
2. Add Web Scrobbler
3. Click the Web Scrobbler icon in the Extensions menu
4. Click the "Open Options Page" button (Gear in the bottom-right corner)

**Expected behavior**
The Web Scrobbler options page opens, without crashing the browser or breaking the extension.

**Debug logs**
Following the instructions laid out on the debug the extension page, I still cannot figure out how to grab logs, either of the background script or of the options page, I'm unsure if this is because of the recent updates, because I am using an uncommon browser, or both.

**Environment (please complete the following information)**
-   OS: Windows 10
-   Browser: Vivaldi Browser
-   Extension version: I'm not sure how to check, but I believe it to be the most recent version, as it has the new icon, and I just reinstalled it and was still able to repeat the bug.

**Additional context**
I never had this issue or a similar one before today, so I suspect it's related to one of the most recent updates. 
I am still able to access the options page by right clicking the extension icon, and then clicking the "Options" button in the drop down; only by clicking the options button in the Web Scrobbler display will it crash.

**Comment by Pekito** [comment] 2023-05-27 23:34
Did some investigation and I think this is related to how Vivaldi is interpreting `target="_blank"` links inside the extension

**Comment by yayuyokitano** [comment] 2023-05-28 06:17
Thank you for reporting! This seems to be a vivaldi exclusive bug.
This will be high priority and should be fixed later today.

**Comment by yayuyokitano** [comment] 2023-05-28 07:28
Interesting, V2 actually crashes too, this seems to be caused by a vivaldi update rather than a web scrobbler update.
Still looking for a workaround.

**Comment by Pekito** [comment] 2023-05-28 07:35
> Interesting, V2 actually crashes too, this seems to be caused by a vivaldi update rather than a web scrobbler update. Still looking for a workaround.

What do you think about using `chrome.tabs.create` to handle these link openings? In my mind this seems to fix the issue but it's tons of work

**Comment by yayuyokitano** [comment] 2023-05-28 07:37
I think it's probably good. I'm currently in the process of wrapping all the anchor tags in popups into an abstraction, so it won't be hard.

**Comment by yayuyokitano** [comment] 2023-05-28 08:54
Got the patch working, just doing some testing now to make sure it doesnt break other browsers then hotfixing

**Closed** 2023-05-28 09:41 UTC
Labels: bug

**Comment by yayuyokitano** [comment] 2023-05-28 09:54
3.0.7 has been pushed with hotfix, just waiting for google to approve now.
