### ISSUE TITLE
Domain "web-scrobbler.com" has expired

### ISSUE THREAD

**Issue by mdn522** [web-scrobbler/web-scrobbler#3273] opened 2022-06-06 05:16 UTC
> This domain is pending renewal or has expired. Please contact the domain provider with questions.

**Comment by inverse** [comment] 2022-06-06 07:00
Thanks for the heads up. Will try to get that renewed

**Comment by alexesprit** [comment] 2022-06-06 09:27
We're moving to another registrar (Namecheap), as the current one (Domain.com) sucks. The transfer should be complete in 5-7 days.

I'll reply with the transfer status update.

**Comment by inverse** [comment] 2022-06-27 08:39
@alexesprit did we get an update from them?

**Comment by alexesprit** [comment] 2022-06-27 09:12
> The current registrar, Domain.com, for the domain [web-scrobbler.com](http://web-scrobbler.com/) rejected
the transfer request you submitted because of Initial 60 Days after icann trade.

IIRC we can retry as I've changed contact information on Apr 23. Will do it later today.

**Comment by alexesprit** [comment] 2022-06-28 06:17
Good news from Domain.com :)

![image](https://user-images.githubusercontent.com/1119267/176106801-e38ae05f-79b7-4cdd-883b-a4fb6e7fbbb5.png)

**Comment by alexesprit** [comment] 2022-07-03 10:39
It's available again. Please note that I've just updated DNS settings, and it might take a while to be applied for everyone. For example it's still not available for me when I'm under my VPN.

The domain and DNS is controlled by Namecheap right now; the domain is expired on Jun 2, 2023. I believe Namecheap will renew it automatically if we have sufficient funds on our Namecheap account.

@inverse please confirm you have access to Namecheap dashboard.

Let me know if it won't work in 24 hours.

<details>
  <summary><b>Screenshot</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/177035692-bffed575-c134-40d9-96d0-4d384cffd97c.png)
</details>

**Closed by alexesprit** 2022-07-03 10:39 UTC
Labels: bug, maintenance

**Comment by inverse** [comment] 2022-07-03 16:28
Confirmed working for me and with access to Namechep. Thanks @alexesprit :pray:

**Comment by inverse** [comment] 2022-07-03 16:35
Did you use Opencollective? We can try and set it up to auto renew wiith that to avoid having issues.
