### ISSUE TITLE
[Feature Request][Youtube] Split scrobbles according to timecodes parts

### ISSUE THREAD

**Issue by BilliAlpha** [web-scrobbler/web-scrobbler#2445] opened 2020-06-09 10:32 UTC
Hello,

Youtube recently added a system to split a video in parts according to timecodes in the video description.
![youtube_part_timecode_list](https://user-images.githubusercontent.com/17186697/84137569-2fd65200-aa4d-11ea-821b-d123f4721368.jpg)

It shows the current part name in the controls just beside the time.
![youtube_part_timecode](https://user-images.githubusercontent.com/17186697/84137572-31077f00-aa4d-11ea-9c24-d23047ddd485.jpg)

It would be great to scrobble the different tracks in a long mix according to this information instead of scrobbling the whole mix as one track.

I might try to do a pull request if I find time.

**Comment by alexesprit** [comment] 2020-06-09 13:40
Closed as a duplicate of #2371.

See my comment for details: https://github.com/web-scrobbler/web-scrobbler/issues/2371#issuecomment-616789168.

**Closed by alexesprit** 2020-06-09 13:40 UTC
Labels: feature

**Comment by BilliAlpha** [comment] 2020-06-09 14:50
Sorry for the duplicate, searched for it but didn't find that request.
