### ISSUE TITLE
Support scrobbling to ListenBrainz

### ISSUE THREAD

**Issue by goodevilgenius** [web-scrobbler/web-scrobbler#1689] opened 2018-08-17 17:11 UTC
### Current behavior

Currently, Web Scrobbler supports scrobbling to Last.fm and Libre.fm. It would be useful if [ListenBrainz](https://listenbrainz.org/) was also supported.

### Possible solution

https://listenbrainz.readthedocs.io/en/latest/dev/api.html

### Context

I'd like to be able to move away from using Last.fm, but I'd rather not have to import my Last.fm data into ListenBrainz, so I'd prefer if Web Scrobbler could scrobble directly to it.

**Comment by oz10h** [comment] 2018-08-17 23:50
https://github.com/web-scrobbler/web-scrobbler/pull/1679

**Comment by woj-tek** [comment] 2018-09-08 08:17
duplicate of #1394 ?

**Comment by inverse** [comment] 2018-09-12 08:00
Dupe - closing

**Closed** 2018-09-12 08:00 UTC
