### ISSUE TITLE
Scrobble individual tracks from mix videos

### ISSUE THREAD

**Issue by endolith** [web-scrobbler/web-scrobbler#2385] opened 2020-04-29 14:44 UTC
**Is your feature request related to a problem? Please describe.**
Scrobbles vague things like "♫ Best Progressive House Mix 2018 Vol. #1 ♫" which are not actually track names

**Describe the solution you'd like**
I didn't know this even existed, but videos like https://www.youtube.com/watch?v=YJwx72g9PwI have the metadata for individual tracks displayed as they play:

![image](https://user-images.githubusercontent.com/58611/80609537-33b29580-8a06-11ea-8d16-d548e97d1a34.png)

Is it possible to extract this info and scrobble each track individaully?

**Comment by alexesprit** [comment] 2020-04-29 16:06
Closed as a duplicate of #2371.

**Closed by alexesprit** 2020-04-29 16:06 UTC
Labels: feature

**Comment by alexesprit** [comment] 2020-05-09 11:49
I added support for MediaSession API in v2.31.0. This API is used to provide track metadata for external applications; e.g. Chrome-browser browsers use them for displaying now playing tracks in a popup window.

![image](https://user-images.githubusercontent.com/1119267/81472935-ccfe5a80-9203-11ea-8e7f-1c0c0ae51360.png)

Unfortunately, the MediaSession API does not provide chapters info. If you use any Chrome-based browser, and you notice it's changed (you'll see a correct artist name/a track title in that popup window), please let me know.
