### ISSUE TITLE
doesn't scrobble listenonrepeat.com

### ISSUE THREAD

**Issue by va91k** [web-scrobbler/web-scrobbler#1958] opened 2019-04-17 10:43 UTC
For example https://listenonrepeat.com/?v=kRFBeOp2L44&s=&e=#Idris_%26_Leos_-_%D0%A0%D0%B5%D0%BA%D0%B0
I see the message that I need to play music.

**Comment by alexesprit** [comment] 2019-04-17 12:30
Closed as a duplicate of #1736.

**Closed by alexesprit** 2019-04-17 12:30 UTC
Labels: duplicate
