### ISSUE TITLE
Short songs (longer than 30 seconds, less than 3-4 minutes) often don't scrobble

### ISSUE THREAD

**Issue by claphands** [web-scrobbler/web-scrobbler#1588] opened 2018-03-02 03:53 UTC
I assume there is an issue with how the app reads duration from google play music. Not sure if this is gplay music specific or more general. It seems to be getting the wrong duration from the file and then generates the wrong "track will be scrobbled in xxx seconds" which is often larger than the track length! 

### Expected behavior
Tracks more than 30 seconds long should scrobble when played on google play music

### Current behavior
Many (not all) shorter tracks don't scrobble. Generally tracks less than 3 minutes don't scrobble

### Steps to reproduce (for bugs)
Here is an example of what happens with a track that is 100 seconds long.  Now playing notification is generated, but duration is given as 367 (seconds??). Time to scrobble is 182.5. Song doesn't scrobble. 

For example:

_Tab 596: New song detected: {
  "track": "Barritones",
  "artist": "Damon Wild",
  "album": "Cosmic Path",
  "uniqueID": null,
  "duration": 367,
  "currentTime": 278,
  "isPlaying": true,
....
controller.js:558 Tab 596: The song will be scrobbled in 182.5 seconds_

Same song to attempt to repeat issue. Now detects duration as 346 and scrobble time at 173. Song doesn't scrobble.

 _Tab 596: New song detected: {
  "track": "Barritones",
  "artist": "Damon Wild",
  "album": "Cosmic Path",
  "uniqueID": null,
  "duration": 346,
  "currentTime": 242,
  "isPlaying": true,
...
Tab 596: The song will be scrobbled in 173 seconds_

Not sure if any additional debug output is useful

### Environment

* Version used: 2.3.5
* Browser name and version: Chrome 64.0.3282.186

**Comment by claphands** [comment] 2018-03-05 00:17
Looking at debug output again, I believe what is happening is that the code that detects duration is getting duration from some *previous* track in an inconsistent fashion. For example in the debug output here:

https://pastebin.com/MemFEB6X

First song "loop_nov25" is actually 97 seconds. System detects it as 234 seconds, so it does not scrobble.
Second song "Warm Wind" is actually 304 seconds. System detects it as 97 seconds. It scrobbles and then the system detects that it has played a second time with the correct duration (304 seconds). It then scrobbles again.
Third song "loop_nov25" again is now detected as having a duration of 304 seconds, so it does not scrobble. 

Summing up what happened for this entire album:
(164 was the accurately detected duration of the last song of the preceding album)
Track 1 real duration 215, detected duration 164, scrobbles once.
Track 2 real duration 340, detected duration 164, scrobbles once.
Track 3 real duration 234, detected duration 164, scrobbles once.
Track 4 real duration 210, detected duration 234, scrobbles once.
Track 5 real duration 146, detected duration 234, scrobbles once.
Track 6 real duration 162, detected duration 234, scrobbles once.
Track 7 (loop_nov25) real duration 97 seconds, detected duration 234, doesn't scrobble
Track 8 (warm wind) real duration 304 seconds, detected duration 97 seconds, scrobbles twice. Duration for second inaccurate scrobble is given as 304 seconds.
Track 7 (loop_nov25 played again) real duration 97 seconds, detected duration 304 seconds, doesn't scrobble. 

No idea what is actually going on under the hood, but this is the output I'm getting. Thanks for any and all help you might be able to offer!

**Comment by alexesprit** [comment] 2018-03-05 23:34
> Looking at debug output again, I believe what is happening is that the code that detects duration is getting duration from some previous track in an inconsistent fashion.

If it happens when the browser is minimized, or the tab with GPM is not active, this is known issue, and I have no idea how to bypass it.

**Comment by claphands** [comment] 2018-03-05 23:40
Thanks for your reply! This seems to be something on the google api side then, per these threads about it for the gplay music desktop player :(

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3018
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/pull/3023

**Comment by keemyb** [comment] 2018-05-20 14:43
How can I help out with some debug data?

I have had this problem using both GPM and Amazon Music.

**Comment by alexesprit** [comment] 2019-05-07 18:40
@claphands  Fixed the issue in https://github.com/alexesprit/web-scrobbler/tree/feature/gpm-inject, but haven't really tested yet.

Feedback is welcome.

The possible regressions are:
- Ads could scrobble (I can't test it because of subscription).
- Option to scrobble podcasts doesn't work.

**Comment by tombriden** [comment] 2019-05-15 06:52
I was also losing scrobbles but this branch is working well for me in Chrome. I do get a Gnome notification for each new track that starts playing (can't remember if that was existing behaviour), but I can live with that if it means all tracks get scrobbled

**Comment by alexesprit** [comment] 2019-05-15 13:57
@tombriden yes, it works perfectly on Chrome and Chrome-based browsers, but not Firefox. Until we find a way to get it worked on Firefox, this fix won't be published.

**Comment by alexesprit** [comment] 2019-09-05 19:11
The best solution is to remove duration getter from the GPM connector.

**Comment by RAM237** [comment] 2019-11-15 20:34
I think I have experienced similar behavior on Yandex Music too, from time to time...

**Comment by alexesprit** [comment] 2019-12-07 21:25
I'm closing this one as we cannot fix the connector due to GPM website limitations. Unfortunately, the Chrome-only fix is a hack and it's not acceptable.

**Closed by alexesprit** 2019-12-07 21:25 UTC
Labels: bug, connector
