### ISSUE TITLE
Some Youtube songs not scrobbling

### ISSUE THREAD

**Issue by XaviPlones** [web-scrobbler/web-scrobbler#2718] opened 2021-01-27 07:18 UTC
Almost every song doesn't scrobble, they're stuck on "searching". The scrobbler is working fine only with songs from "Topic" channels
 
Songs were supposed to scrobble, i have scrobbled them with this app and on this pc, but it is just not working

**Environment (please complete the following information)**
-   OS:  Windows 10
-   Browser: Edge Chromium
-   Extension version: 2.40.0

**Comment by alexesprit** [comment] 2021-01-27 09:01
Have you any examples of videos that aren't scrobbled?

Also, [how to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by alexesprit** [comment] 2021-01-27 09:06
<details>
  <summary><b>Screenshot</b> (Click to expand)</summary>

![image](https://user-images.githubusercontent.com/1119267/105968406-1b0c0480-6098-11eb-8b13-c7573224acc3.png)
</details>

**Comment by KnowsyKnowsBest** [comment] 2021-01-27 09:17
This one doesnt scrobble for me
https://youtu.be/sxGV2RYC7zA

**Comment by KnowsyKnowsBest** [comment] 2021-01-27 09:22
Here is my debug-blog. This is the first time ive ever posted one of these so hopefully i got what you need
https://pastebin.com/tg20kXHk

**Comment by alexesprit** [comment] 2021-01-27 09:28
Aha, I see. Will check this.

**Comment by alexesprit** [comment] 2021-01-27 09:53
The issue is not related to YouTube.

We use MusicBrainz API to fetch cover arts from CoverArtArchive. Currently, musicbrainz.org is down, but the extension waits for response (about 30 seconds per each request, and we send up to 2 requests per one song). I guess it will be available again in few hours.

I'll reduce timeouts in the next version. I see no reasons to fix it ASAP - it takes about one-two days to publish the extension to stores.

**Comment by alexesprit** [comment] 2021-01-27 10:08
I'm closing this in favor of #2720.

**Closed by alexesprit** 2021-01-27 10:08 UTC
Labels: bug, can't reproduce

**Comment by XaviPlones** [comment] 2021-01-27 16:01
It is working just fine today hahah, thx
