### ISSUE TITLE
No scobbling Spoitfy 

### ISSUE THREAD

**Issue by shodate76** [web-scrobbler/web-scrobbler#3108] opened 2022-01-26 10:07 UTC
The  scrobler  not picking  music being played i pay  muisc the sybol jus stays red and doe s tun green 

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS:  Widows  10   Full updated   i upated to mosrrecant verison today
-   Browser:  all  that in use   FF   CG   Op
-   Extension version: 2.50.0

**Additional context**

**Comment by inverse** [comment] 2022-01-26 20:04
Duplicate of #3105

**Closed by inverse** 2022-01-26 20:04 UTC
Labels: bug
