### ISSUE TITLE
Add extension support for Safari

### ISSUE THREAD

**Issue by jinyuzu99** [web-scrobbler/web-scrobbler#1908] opened 2019-02-10 03:57 UTC
Chrome spends too much RAM and battery, Safari is a better choice for long time music playback on MacBook.

**Comment by damienix** [comment] 2019-11-27 12:20
Switched to Safari for the very same reasons and need a Youtube scrobbler...

**Comment by hans-juergen** [comment] 2019-12-27 05:51
Right, it would be the logical next step for Apple users who want to scrobble the new [Apple Music web player](https://beta.music.apple.com/) now that Web Scrobbler supports it in other browsers.

**Comment by hans-juergen** [comment] 2020-05-31 07:47
I'd like to add that the only available Safari browser extension scroblr (which also supported Chrome) is gone with the wind now, i.e. neither available in the Chrome store nor on their website anymore. Their GitHub page still exists though:

https://scroblr.fm
https://github.com/cgravolet/scroblr

So supporting Safari might be more urgent now, unfortunately I do not use this browser or any Apple soft- and hardware.

**Comment by alexesprit** [comment] 2020-05-31 08:09
This is a quite hard task to do, since Web Scrobbler is powered on WebExtensions, and Safari does not support WebExtensions. That means we should add a layer to switch between different APIs.

I do not use macOS too, and have no Apple devices, so it becomes harder for me to add support.

**Comment by hans-juergen** [comment] 2020-05-31 08:26
Could you fork the available source code from scroblr perhaps? You would only need the Safari part of course.

**Comment by alexesprit** [comment] 2020-05-31 08:34
There's no "Safari part" in that extension. Safari's API are used everywhere in source code. We cannot just fork and copy them.

**Comment by hans-juergen** [comment] 2020-05-31 09:24
OK - too bad that the rumour end of last year of Apple supporting the Chromium engine in a new Safari version was just a fake.

**Comment by inverse** [comment] 2020-05-31 19:17
Added "help wanted" since none of us are safari/mac users.

**Comment by stejmurphy** [comment] 2020-06-25 08:33
Safari 14, upcoming for a September/October 2020 release will support Web Extensions.

https://developer.apple.com/documentation/safariservices/safari_web_extensions

Also worth noting that we should expect Safari 14 to be made available on macOS Mojave and Catalina too. Apple tend to support the previous two OSs to the current one.

**Comment by alexesprit** [comment] 2020-06-25 08:51
Wow, sounds awesome.

I expect some compatibility issues, like Firefox. Plus, we should manage building and releasing too.

**Comment by hans-juergen** [comment] 2020-06-25 09:27
Great news indeed!

**Comment by stejmurphy** [comment] 2020-06-25 11:01
@alexesprit I would definitely expect Apple to make it harder. From reading the the doc on the link above, you still have to use Xcode.

But it's a sort of a step in the right direction.

**Comment by mountainash** [comment] 2020-06-25 14:50
> @alexesprit I would definitely expect Apple to make it harder.

You also have to submit it to Apple’s App Store so I guess you’ll also need a {paid} developer account.

**Comment by dannysood** [comment] 2020-09-24 19:52
Any news on this. You can always go Dark Reader dark mode extension route where because they paid for a developer account the extension can be paid instead of free. Ill love to buy extension for for safari support.

**Comment by dannysood** [comment] 2020-09-24 20:11
I am also an mac user and long time typescript/nodejs developer.  So I can take the responsibility to releasing this to mac. I'll need some help porting this though.

**Comment by Scvairy** [comment] 2020-10-26 13:09
Can it be packed in Userscript? As a temporary solution

**Comment by alexesprit** [comment] 2020-10-26 13:52
No, it can't. See https://github.com/web-scrobbler/web-scrobbler/issues/2456#issuecomment-647419256 for details.

**Comment by mountainash** [comment] 2021-02-19 07:38
Why the close @sayomelu? 

I was excited to come  back to the project to see if a Safari Extension had been released... but I can't see it. Have you found an alternative?

**Comment by pixiekat** [comment] 2021-06-08 23:54
Came back to see if any possibility for support post WWDC, especially iOS/iPadOS support. :)

**Comment by hans-juergen** [comment] 2021-06-09 14:12
The We Scrobbler browser extension does not work on these OS versions, only in desktop browsers. If you want to scrobble Apple Music on iOS, there are some scrobbling apps, e.g. QuietScrob has a new version which can also scrobble streamed Apple Music songs, not only those songs that you have added to your Music library first.

**Comment by mountainash** [comment] 2021-06-09 21:03
Thanks for the in-depth misdirected explanation @hans-juergen but I believe this issue was created as a request to expand the extension to also work on Safari, and @pixiekat was adding the new fact that the next iOS/iPad versions of Safari will also support extensions. 

News: https://9to5mac.com/2021/06/07/apple-brings-safari-web-browser-extensions-to-iphone-and-ipad-with-ios-15/

**Comment by mountainash** [comment] 2021-06-10 19:10
Just adding some WWDC resource links to help anyone with this new feature:
- https://developer.apple.com/wwdc21/10104
- https://developer.apple.com/wwdc21/10027

**Comment by mountainash** [comment] 2022-02-14 16:51
<img width="919" alt="Safari Preferences showing Web Scrobbler Extension installed" src="https://user-images.githubusercontent.com/27637/153907870-1357c331-3672-4a6b-8e96-bc9d70946226.png">

... only just last weekend I finally had time for a play. It's a long way from working well enough for distribution, but I got it to a point where I can start to debug.

One limitation that I've hit already is that Apple don't allow extensions to trigger OS style notifications... so that will never work, but it's not a critical part of the extension IMO.

I'll try and find some more time to work on it soon. I'll also need to chat with this projects maintainer on how to release it, as it would need an Apple App Store account (and they'd most likely like to control it).

**Comment by mountainash** [comment] 2022-02-18 13:53
Some good news: at 4 am this morning (after hours of trial-and-error), I was able to get Web Scrobbler in Safari to scrobble it's [first track](https://www.last.fm/user/mountainash/library/music/Panthurr/_/In+Parallel) played on Soundcloud to Last.fm.

There's quite a bit of work needed for the pop-up UI, but it's good that the fundamentals are achievable.

<img width="394" alt="Screenshot of the broken pop-up track info on Safari Tech Preview" src="https://user-images.githubusercontent.com/27637/154695157-134c2a78-eec7-46e5-859e-1c5cc15b0401.png">


I've since tested with success plays from, Youtube, Youtube Music, Spotify, Hypemachine & Last.fm itself (as a player) - but connectors for Mixcloud, 8tracks, abc.net.au, Bandcamp don't seem to discover tracks playing - and that's only after some quick tests.

**Comment by mountainash** [comment] 2022-02-19 16:32
Anyone subscribed to this issue - I've started a Discussion to get some feedback on developing this task further. I'd really value your input: https://github.com/web-scrobbler/web-scrobbler/discussions/3139

**Comment by mountainash** [comment] 2022-03-02 15:41
Some further updates... (the popup UI) is now working.
<img width="474" alt="Screen Shot showing the Web Scrobbler extension popup" src="https://user-images.githubusercontent.com/27637/156395263-30bc9103-8cab-4ba8-a188-a4b2fa87887c.png">

**Comment by mountainash** [comment] 2022-03-02 15:58
Oh and bad news for anyone thinking about running it in Safari on iOS.

> Extensions on iOS must have a non-persistent background page.

![iPhone screenshot showing warning message when enabling the extension on iOS]()

**Comment by mountainash** [comment] 2022-03-02 19:20
Something else I worked on over the weekend:

<img width="474" alt="Web Scrobbler icon in a Safari flavour" src="https://user-images.githubusercontent.com/27637/156433144-c424cd29-6601-445e-865e-fc92ef00cce0.png">

**Comment by inverse** [comment] 2022-03-02 21:04
@mountainash awesome! Please share in https://github.com/web-scrobbler/web-scrobbler/issues/2430

**Comment by bs** [comment] 2022-03-28 20:11
I’d just like to say how much I appreciate this work. Thank you, @mountainash.

**Comment by yayuyokitano** [comment] 2022-06-11 15:24
> Oh and bad news for anyone thinking about running it in Safari on iOS.
> 
> > Extensions on iOS must have a non-persistent background page.
> 
> <img alt="iPhone screenshot showing warning message when enabling the extension on iOS" width="474" src="https://user-images.githubusercontent.com/27637/156398958-652393df-f4cd-4758-b7da-acb0ad71dbe2.jpeg">

Some addition on this and on the issue in general.

Eventually, with the movement to manifest v3, the entire extension must be rewritten to stop using persistent background page.

Currently waiting for firefox to gain full v3 support before it must be implemented before the end of the year.

Currently it's looking like I will be the one to do this implementation when the time comes, and since I use mac as main machine, I will probably attempt to write this new version to support both safaris out of the box, but at this stage I am not willing to make any promises.

**Comment by mountainash** [comment] 2022-06-13 05:49
> Eventually, with the movement to manifest v3, the entire extension must be rewritten to stop using persistent background page.

Really? That doesn't match with what Chrome is saying here in the v3 docs [Register background scripts](https://developer.chrome.com/docs/extensions/mv3/service_workers/#manifest)

But I believe that the plugin could be written to just inject some code into the various sites themselves that attaches to the audio events and directly submits the "listens" back to the various tracking/counting services - it doesn't necessarily have to happen in a background worker.

**Comment by yayuyokitano** [comment] 2022-06-14 06:06
> > Eventually, with the movement to manifest v3, the entire extension must be rewritten to stop using persistent background page.
> 
> Really? That doesn't match with what Chrome is saying here in the v3 docs [Register background scripts](https://developer.chrome.com/docs/extensions/mv3/service_workers/#manifest)
> 
> But I believe that the plugin could be written to just inject some code into the various sites themselves that attaches to the audio events and directly submits the "listens" back to the various tracking/counting services - it doesn't necessarily have to happen in a background worker.

Perhaps refactor would've been a better word than rewritten, but the spirit of what I said I don't think contradicts what V3 docs are saying.
Similar to non-persistent V2 background scripts, V3 service workers are purely event driven.
After usually about 5 minutes (but no time can be guaranteed), the service worker will die and any state you had will die with it.
I think the only meaningful difference between non-persistent V2 background scripts and V3 service workers is you can use webrequest with V3 service workers, but web scrobbler does not use that API anyway so it is irrelevant. There might be more though.
I strongly suspect that once iOS safari gains support for V3 there might not be any need for additional changes to the code over supporting other browsers in V3.

Indeed, more than likely the migration will involve moving a fair amount of the logic to content script, but I have not looked into the exact details just yet.

**Comment by Brin-o** [comment] 2022-08-10 07:46
Hi, whats the status on this? Can I give a donation somewhere to support getting it working on Safari?

**Comment by yayuyokitano** [comment] 2022-08-10 08:39
I can guarantee manifest V3 migration will occur by the end of the year. It however has not changed that firefox remains not in full support of V3 (they say late 2022). Ideally, we wait for this before proceeding, as migrating before this would introduce quite a few complications.

With manifest V3 migration Safari support *probably* also isnt too hard to implement, but again, I'm not willing to make any sweeping guarantees just yet.

Typescript migration probably happens in the meantime, should make V3 migration easier.

You are free to donate to our opencollective if you would like to, however it won't really affect our timeline.

Thank you for your patience.

**Comment by TareqAmeer** [comment] 2022-09-18 16:49
Any updates on this :)

**Comment by yayuyokitano** [comment] 2022-09-18 17:26
> Any updates on this :)

Work on the typescript migration has started.

Start of manifest V3 work still pending, but will probably start not super ling after typescript is done.

ETA for manifest V3 remains sometime towards the end of the year.

I still have not found any reason to believe safari support can't be implemented with manifest V3 migration.

**Comment by RorPieTh** [comment] 2022-12-30 06:23
Hello there. This project seems to be my only hope for scrobbling Bandcamp on Mac, since I just use Safari. Any update?

thanks for the hard job!

**Comment by yayuyokitano** [comment] 2022-12-30 10:32
Hi, I was thinking to make an update here, but never got around to it.
So, obviously, there has been a delay here.

Essentially, Google has pushed back the date for manifest V3 until June 2023.
With me having had a few months that were way more busy than I expected, I chose to lay my projects on ice for a bit.
I imagine I will be able to finish up the typescript rewrite in February.

This would put the new date for the manifest V3 rewrite to probably March.
It remains that I think safari support can be done along with the manifest V3 rewrite.

**Comment by yayuyokitano** [comment] 2023-03-14 00:04
V3 is running in Safari and all the things that work in chrome/firefox seem to be working in Safari too. Still a bit more work to go before it is ready for release though, but not that much left.

**Comment by yayuyokitano** [comment] 2023-03-21 22:37
@mountainash do you happen to have the safari icon lying around still, and if so, would you be down to open a PR to commit it to the icons folder asap? If not its nbd, I should be able to get something worked out pretty quickly.

**Comment by mountainash** [comment] 2023-03-21 23:22
What "nbd" mean? 

I'm not at my computer ATM but will be in the morning (~8hrs) if you can wait?

**Comment by yayuyokitano** [comment] 2023-03-21 23:28
It means no big deal.

8hrs is plenty fast! Thank you!

**Comment by TareqAmeer** [comment] 2023-06-10 09:46
Is this now available to install?

**Comment by yayuyokitano** [comment] 2023-06-10 09:52
We are going through a review back and forth with apple. I will close the issue when it is available for install. I think we are talking days.

**Comment by yayuyokitano** [comment] 2023-07-04 03:47
Ended up taking longer than thought, but it should be out now! On Safari for macOS as well as iOS/iPadOS

Should be here, are people able to download? https://apps.apple.com/app/web-scrobbler/id6449224218

**Comment by yayuyokitano** [comment] 2023-07-04 03:49
Also this will probably be a bit unstable and some UI might be janky etc, especially the iOS version, but I havent run into any big issues yet at least

**Comment by mountainash** [comment] 2023-07-04 04:05
> Ended up taking longer than thought, but it should be out now! On Safari for macOS as well as iOS/iPadOS

Yay, but what's that ugly logo 😭 Did you want to use [this](https://github.com/web-scrobbler/web-scrobbler/pull/3599)?

**Comment by yayuyokitano** [comment] 2023-07-04 04:07
> > Ended up taking longer than thought, but it should be out now! On Safari for macOS as well as iOS/iPadOS
> 
> Yay, but what's that ugly logo 😭 Did you want to use [this](https://github.com/web-scrobbler/web-scrobbler/pull/3599)?

Apple did not allow the usage of the lastfm logo

**Comment by hans-juergen** [comment] 2023-07-04 09:22
> Ended up taking longer than thought, but it should be out now! On Safari for macOS as well as iOS/iPadOS
> 
> Should be here, are people able to download? https://apps.apple.com/app/web-scrobbler/id6449224218

Great news, thank you! As I do not use Safari on my Windows 10 PC anyhow, I tried to install the iOS version from the App Store on my old iPhone 6s Plus with iOS 15.7.7 which seems to have worked. I then opened YouTube in the iOS Safari version and started a playlist, but currently there are no scrobbles coming through, maybe I need to restart the browser. I had confirmed the message that Web Scrobbler should support YouTube before.

**Comment by yayuyokitano** [comment] 2023-07-04 09:53
> > Ended up taking longer than thought, but it should be out now! On Safari for macOS as well as iOS/iPadOS
> > Should be here, are people able to download? https://apps.apple.com/app/web-scrobbler/id6449224218
> 
> Great news, thank you! As I do not use Safari on my Windows 10 PC anyhow, I tried to install the iOS version from the App Store on my old iPhone 6s Plus with iOS 15.7.7 which seems to have worked. I then opened YouTube in the iOS Safari version and started a playlist, but currently there are no scrobbles coming through, maybe I need to restart the browser. Or I have to check in the settings that I am connected and authorised in my Last.fm account. I had confirmed the message that Web Scrobbler should support YouTube before.

Youtube is supported and verified working on my end iOS. If you have enabled the extension correctly, you should be able to bring up the web scrobbler popup by clicking the little icon on the left side of the url bar and then clicking web scrobbler underneath manage extensions, where you can see more information about whats going on.

**Comment by hans-juergen** [comment] 2023-07-04 10:19
Thanks for your explanation, I had not logged into my Last.fm account yet with the new Web Scrobbler on iOS of course. It's scrobbling the same playlist fine now. 😊

**Comment by TareqAmeer** [comment] 2023-07-09 00:04
Thanks for all the work!!

I can't seem to login into Last.fm, nothing happens when i click the button. It did work for Libre.fm.


Using Safari v16.5

<img width="1007" alt="Screenshot 2023-07-09 at 12 59 40 AM" src="https://github.com/web-scrobbler/web-scrobbler/assets/74020139/b3059364-87d3-4f14-b109-6e46e5d5d5d8">

**Comment by hans-juergen** [comment] 2023-07-09 02:53
Last.fm had some site issues today, see e.g. the banner on top of the support forum or their status page on Twitter:

https://twitter.com/lastfmstatus/status/1677743887316656128

But now the site is back up, so maybe just try again to login.

**Comment by TareqAmeer** [comment] 2023-07-14 19:30
I've uninstalled and reinstalled everything, turned off any other extensions and still nothing happens when i click that button :/

**Closed** 2024-01-06 22:18 UTC
Labels: feature, core, help wanted
