### ISSUE TITLE
Add Turntable.FM

### ISSUE THREAD

**Issue by neeshcast** [web-scrobbler/web-scrobbler#2772] opened 2021-03-15 09:05 UTC
Turntable.FM is back (password: speakeasy) after being shut down for 8 years. I believe this extension used to scrobble it. The website now streams music through youtube (and soundcloud). I would love to be able to scrobble the music!

Thanks so much.

**Comment by alexesprit** [comment] 2021-03-15 09:09
Closed as a duplicate of #2752.

Support for turntable is already added and will be available in the next version.

**Closed by alexesprit** 2021-03-15 09:09 UTC
Labels: connector, request
