### ISSUE TITLE
Stopped with scrobbling after update.

### ISSUE THREAD

**Issue by ChineseOuchie** [web-scrobbler/web-scrobbler#1911] opened 2019-02-10 20:44 UTC
error message: 
![image](https://user-images.githubusercontent.com/10912994/52539317-ff10da80-2d7c-11e9-8711-c73904d182b7.png)

Windows 8.1

Chrome Version 71.0.3578.98

**Comment by rohitps** [comment] 2019-02-11 01:18
Same issue in Win 10/Firefox 65.

**Comment by inverse** [comment] 2019-02-11 20:51
Got a sample URL?

**Comment by rohitps** [comment] 2019-02-12 00:32
> 
> 
> Got a sample URL?

Any Youtube music video: https://www.youtube.com/watch?v=TJAfLE39ZZ8

Get the error : 
Unable to get category for TJAfLE39ZZ8: Invalid response

**Comment by nightwica** [comment] 2019-02-12 20:55
Yup, it just tells me (Chrome addon) to play some music.. But my Youtube is already playing a music video.

**Comment by cfare** [comment] 2019-02-13 20:23
I have the same issue, reproducible on latest master. Looks like the Youtube API request to get the video category is returning a 403.

**Comment by nightwica** [comment] 2019-02-13 21:42
Today it already worked for me!

**Comment by alexesprit** [comment] 2019-03-10 08:14
Should be fixed in v2.15.0 and newer.

**Closed by alexesprit** 2019-03-10 08:14 UTC
Labels: bug, connector
