### ISSUE TITLE
Web Scrobbler not working on Bandcamp

### ISSUE THREAD

**Issue by diegodasro** [web-scrobbler/web-scrobbler#2585] opened 2020-10-06 19:04 UTC
So, I'm using the extension for Firefox for some time to scrobble from Bandcamp and it always worked perfectly but since yesterday, the scrobbler isn't working.
(I tested with Soundcloud and it works well, the problem seems to be Bandcamp only, also I tested with Chrome and the problem is the same.)

1. Open Bandcamp page
2. Play a track
3. Appears a 'magnifier' symbol(?) on the scrobbler icon saying 'Buscando por null' (I am brazilian, the translation may be 'seaching for null').
4. It stays searching for something and the scrobble doesn't work.
![Sem título](https://user-images.githubusercontent.com/72467269/95248138-3f905800-07ed-11eb-9f59-93e79358f234.png)

- Windows 10
- Mozilla Firefox 81.0.1 (64-bits)
- Extension version 2.36.0

This is my first post here and english isnt my native language so sorry if I wasn't clear enough about the issue.

**Comment by alexesprit** [comment] 2020-10-06 19:10
Duplicate of #2583.

**Comment by alexesprit** [comment] 2020-10-06 19:11
This was already fixed in v2.36.1.

**Comment by diegodasro** [comment] 2020-10-06 19:36
Thanks, its working now!

**Closed** 2020-10-06 19:36 UTC
Labels: bug
