### ISSUE TITLE
Plex Media - Music Various Artists + 1 Bug

### ISSUE THREAD

**Issue by calvinc64** [web-scrobbler/web-scrobbler#1598] opened 2018-03-11 14:21 UTC
1. The Artists which are shown as "Various Artists" on the Playbar:
![image](https://user-images.githubusercontent.com/5560381/37254396-68b811ae-253d-11e8-868c-d47cd7a78884.png)
are not correctly shown in the scrobbler:
![image](https://user-images.githubusercontent.com/5560381/37254472-9c47ecdc-253e-11e8-9853-c29e9395b44a.png)

But I've noticed, that the Tab-Title of the Page contains the right title and Artist.

Additionally I've noticed, that the Tags duplicate if you Maximize the Player:
![image](https://user-images.githubusercontent.com/5560381/37254499-f85a1ebe-253e-11e8-939c-0cd13e225ffe.png)

### Expected behavior

normally the Artist should be shown right.
Also the Tags should not duplicate if the player is maximized

### Current behavior

Various Artists showing instead of the right artist name.

### Possible solution

Maybe you could read the Artist's name from the Browsers Tab name....

### Steps to reproduce (for bugs)

1. Open Plex...
2. Play a Song from a "Various Artists" page but with embedded artist name...
![image](https://user-images.githubusercontent.com/5560381/37254534-72a86090-253f-11e8-927d-55accbbc1a8e.png)

Other bug that I experienced, just click on the album cover from the "Playbar" so that the whole page is only the player.

### Context

Scrobbles not submitting, because they could not be found on LastFM, because there is no Song with "Various Artists"

### Steps for resolving the issue

- [x] Reauthenticate on Last.fm
- [x] Try to use unpacked extension from latest master
- [x] Check other issues for duplicates

### Environment

* Version used: Git Clone from the 11 March 2018. (Added as Dev-App to Chrome)
* Browser name and version:  64.0.3282.186 64Bit (Chrome)

**Comment by calvinc64** [comment] 2018-06-16 15:29
Still waiting here...

**Comment by inverse** [comment] 2018-06-16 16:51
Unfortunately I don't have plex so am unable to test.

The tag duplication seems very odd.

**Comment by calvinc64** [comment] 2018-06-16 16:57
Just download it to your PC, quite easy... just download create an account 4free and then try it your self... you can download the server here: plex.tv

**Comment by alexesprit** [comment] 2019-05-12 07:50
The duplication is fixed in 830893e297dd5f4a40182e38ac685432a9180af8.

I can't reproduce the issue with Various Artists. Probably, it was changed in some Plex version.
![image](https://user-images.githubusercontent.com/1119267/57579358-700e7e00-74a3-11e9-93f8-42748040dcb6.png)

**Closed by alexesprit** 2019-05-12 07:50 UTC
Labels: bug, connector
