### ISSUE TITLE
Amazon Echo/Alexa scrobbles on Firefox are sending playlist name instead of album name

### ISSUE THREAD

**Issue by tchrischan** [web-scrobbler/web-scrobbler#1400] opened 2017-09-13 17:22 UTC
If I play a playlist (either from alexa voice command, or Spotify Connect), the web scrobbler sends the playlist name as the album name.  It sends the album name correctly if I play a song or album by name, or use Your Daily Mix.

### Expected behavior

Album name of song should be scrobbled.

### Current behavior

Playlist name of song scrobbled instead.

### Possible solution

Get the album name from Spotify and use that instead (assuming it's accessible).

### Steps to reproduce (for bugs)

1.  Load Alexa Player website in firefox with web scrobbler add-in.
2.  Ask Alexa to play a playlist from Spotify. 

### Context

I have a bunch of dynamic playlists on my computer that rely on last.fm scrobbles, so bad data is a nuisance for me.

### Steps for resolving the issue

- [ y] Reauthenticate on Last.fm

- [n/a ] Try to use unpacked extension from latest master

- [ y] Check other issues for duplicates

### Environment

* Version used: 1.68.1
* Browser name and version: Firefox 55.0.3 (32-bit)

**Comment by alexesprit** [comment] 2017-09-17 10:47
@puthali could you check this issue and fix it?

**Comment by thedrinkeno** [comment] 2018-04-27 02:04
This is also reproducible by playing something from Pandora on Alexa via Echo voice commands. Instead of the album of the track, the Radio name is scrobbled instead.

There is a musicbrainz api that can possibly be leveraged

https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2/Search

**Comment by matelich** [comment] 2018-08-27 04:17
Also happens on Amazon Music webplayer on Chrome - playlist name is being inserted as album name. I always use playlists, so I'd be happy with just an option to turn off populating the album field

**Comment by inverse** [comment] 2018-09-12 06:49
Will be in fixed in the next release :+1:

**Comment by alexesprit** [comment] 2019-05-12 07:25
Closing this, because #1694 is merged.

**Closed by alexesprit** 2019-05-12 07:25 UTC
Labels: bug, confirmed, connector
