### ISSUE TITLE
20 Buck Spin Bandcamp Connector

### ISSUE THREAD

**Issue by Heckhammer** [web-scrobbler/web-scrobbler#2519] opened 2020-08-09 03:23 UTC
**Provide information about website**
Despite the record label 20 Buck Spin operating on Bandcamp, none of their tracks scrobble from their Bandcamp page.

**Comment by inverse** [comment] 2020-08-09 06:18
I'm guessing it's due to being on a custom domain. You can configure this in the settings for the connector.


What's the URL so we can confirm?

**Comment by Heckhammer** [comment] 2020-08-09 08:10
https://listen.20buckspin.com/music Here's the site in question.
https://listen.20buckspin.com/album/entropic-reflections-continuum-dimensional-unravel Here's a random album off of said website.

Thank you for the help, by the way.

**Comment by alexesprit** [comment] 2020-08-09 09:32
Closed as a duplicate of #334. The solution is described in this comment: https://github.com/web-scrobbler/web-scrobbler/issues/334#issuecomment-62688246.

**Closed by alexesprit** 2020-08-09 09:32 UTC
Labels: bug, connector, needs confirm
