### ISSUE TITLE
Feature Request: Parse youtube description for songs in continuous mixes

### ISSUE THREAD

**Issue by heyarne** [web-scrobbler/web-scrobbler#1682] opened 2018-08-06 15:07 UTC
I have noticed that many continuous mixes / albums etc you find on Youtubue contain some sort of playlist in the description that allows skipping to single tracks. See for example [here](https://www.youtube.com/watch?v=Ff9eDId1GtM). The lists always look very similar to each other, basically `Time - (Artist -)? Title`. Could this maybe be parsed to allow for scrobbling of single tracks in such a playlist? This is more or less loud thinking, but it would be super nice if this worked.

**Comment by myfonj** [comment] 2018-08-06 16:52
Just came here to finally create this very feature proposal I've been planning to create for years to find out it has been created 2h ago :]

This applies perhaps even more to **full album** videos, like e.g. [this one](https://www.youtube.com/watch?v=waKnvlwC11A) where the format is `^Number Title Time$`.  

While looking for the example I accidentally stumbled upon [this iconic album](https://www.youtube.com/watch?v=hu0kGvKujCg) with admittedly nightmarish track titles and structure where proper tracklist is in the "first" comment, so any block containing timestamped links pointing to current video could be considered?

**Comment by PlaylistsTrance** [comment] 2018-12-12 16:22
To add onto this, if a parser isn't possible it would be nice to be able to create the list of tracks with timestamps themselves in the scrobbler menu for the current video.
And save this list for the video so you don't have to do it again.
So when the video hits a certain timestamp it will know what song to scrobble at that time.

**Comment by marsjaninzmarsa** [comment] 2019-01-31 06:36
Dupe of #122 and then #655, there even was some initial work done.

**Comment by PlaylistsTrance** [comment] 2019-01-31 15:58
Right, well, I'm not sure if we need to transfer the discussion to any of those now, but I really think that since a parser didn't seem doable, a manual timestamped tracklist would be a great alternativ.e

**Comment by alexesprit** [comment] 2019-05-04 13:35
Closing this one as a duplicate of #122.

**Closed by alexesprit** 2019-05-04 13:35 UTC
Labels: connector, feature
