### ISSUE TITLE
Youtube cue parsing

### ISSUE THREAD

**Issue by crzsotona** [web-scrobbler/web-scrobbler#2408] opened 2020-05-17 14:39 UTC
Youtube has added some kind of cue sheets, like on desktop, to uploaded tracks, for example this video has it
> 9O4_awEHh1g

Could you add feature to scrobble titles from this cue sheets, as many full albums on youtube still scrobble as single track?

**Comment by alexesprit** [comment] 2020-05-18 03:27
Duplicate of #2371.

**Closed by alexesprit** 2020-05-18 03:27 UTC
Labels: connector, feature
