### ISSUE TITLE
Spotify Web Player Not Scrobbling

### ISSUE THREAD

**Issue by kmehlin** [web-scrobbler/web-scrobbler#2276] opened 2020-02-24 16:25 UTC
https://open.spotify.com/ no longer scrobbling.

**Comment by alexesprit** [comment] 2020-02-24 17:02
Can't reproduce. Works fine for me.

![image](https://user-images.githubusercontent.com/1119267/75173841-9060ae00-5740-11ea-9616-897b1e2a4ccf.png)

**Comment by nekropunk** [comment] 2020-02-24 19:32
didn't work for me for a while either, restarting the browser solved it.

**Comment by Maddieman** [comment] 2020-02-25 14:54
As of today, I'm having a similar issue with spotify, but _only_ for tracks played in the desktop app that I'm trying to scrobble in the web player (I'll explain).

The desktop client streams at a noticeably higher bitrate than their webplayer, but I want to scrobble it using the web scrobbler browser extension so I can edit / correct tags on the fly.  So what I usually do is have https://open.spotify.com/ open in my browser, and then play music normally through the Spotify desktop app.  Normally this works fine, because the webplayer and desktop client are both connected to the same account and spotify updates both with the track and artist name, which the web scrobbler picks up (you see green bar at the bottom of the web player saying "You're listening on ... ").

I guess Spotify have changed something with their web player, because now when I start music in the desktop player, the web scrobbler doesn't detect it (even though the web player still updates with the correct info).  What's interesting though is if you completely shut down the Spotify desktop app and only play music through the Spotify webplayer, the web scrobbler does detect it.

Thanks in advance if anyone can look into this, or shed any light on why it's not working any more.

![web](https://user-images.githubusercontent.com/1643178/75258581-97d69480-57de-11ea-98da-d4f23554bfd2.png)

**Comment by kmehlin** [comment] 2020-02-25 14:59
> As of today, I'm having a similar issue with spotify, but _only_ for tracks played in the desktop app that I'm trying to scrobble in the web player (I'll explain).
> 
> The desktop client streams at a noticeably higher bitrate than their webplayer, but I want to scrobble it using the web scrobbler browser extension so I can edit / correct tags on the fly. So what I usually do is have https://open.spotify.com/ open in my browser, and then play music normally through the Spotify desktop app. Normally this works fine, because the webplayer and desktop client are both connected to the same account and spotify updates both with the track and artist name, which the web scrobbler picks up (you see green bar at the bottom of the web player saying "You're listening on ... ").
> 
> I guess Spotify have changed something with their web player, because now when I start music in the desktop player, the web scrobbler doesn't detect it (even though the web player still updates with the correct info). What's interesting though is if you completely shut down the Spotify desktop app and only play music through the Spotify webplayer, the web scrobbler does detect it.
> 
> Thanks in advance if anyone can look into this, or shed any light on why it's not working any more.
> 
> ![web](https://user-images.githubusercontent.com/1643178/75258581-97d69480-57de-11ea-98da-d4f23554bfd2.png)

Yup, I am in the exact same boat and run both for the same reasons. It worked last week but as you said, the only way to get the scrobbler to work is to shutdown the desktop client.

**Comment by alexesprit** [comment] 2020-02-25 18:42
> I guess Spotify have changed something with their web player, because now when I start music in the desktop player, the web scrobbler doesn't detect it (even though the web player still updates with the correct info). What's interesting though is if you completely shut down the Spotify desktop app and only play music through the Spotify webplayer, the web scrobbler does detect it.

It was made intentionally to satisfy #2242. I think the only way to resolve both issues is to make a new option (I hate options, btw).

**Comment by Maddieman** [comment] 2020-02-26 11:15
Ah, I see. Well it's up to you. :)  It's a bit of an edge case, but then I suppose so is having the spotify web player open in two tabs.

Either way, thanks for your hard work on the web scrobbler.  👍

**Comment by dubeyy** [comment] 2020-02-28 19:26
Also experiencing this..

I scrobble mostly from my desktop computer and play through my Sonos. I've been using web scrobbler to scrobble my plays via Chrome because there's no other working solution.

Closing the desktop app mentioned above doesn't work. What does work is playing via Web through my computer speakers which defeats the purpose of having Sonos speakers in my house.

Curious if anyone else has other workarounds for my situation

**Comment by kmehlin** [comment] 2020-02-28 21:52
> Also experiencing this..
> 
> I listen to music mostly from my desktop computer via the Spotify desktop app and play through my Sonos. I've been using web scrobbler to scrobble my plays via Chrome because there's no other working solution.
> 
> Closing the desktop app mentioned above doesn't work. What does work is playing via Web through my computer speakers which defeats the purpose of having Sonos speakers in my house.
> 
> Curious if anyone else has other workarounds for my situation

I was mostly using the Scrobbler for the pop-up notifications so I could see the song name when the player was in the background. In the interim, I enabled the Spotify connector at Last.fm so the scrobbling is working without the extension, but no pop-ups. Not sure if this helps.

[Last.Fm Application Connector](https://www.last.fm/settings/applications)

**Comment by dubeyy** [comment] 2020-02-28 21:59
> > Also experiencing this..
> > I listen to music mostly from my desktop computer via the Spotify desktop app and play through my Sonos. I've been using web scrobbler to scrobble my plays via Chrome because there's no other working solution.
> > Closing the desktop app mentioned above doesn't work. What does work is playing via Web through my computer speakers which defeats the purpose of having Sonos speakers in my house.
> > Curious if anyone else has other workarounds for my situation
> 
> I was mostly using the Scrobbler for the pop-up notifications so I could see the song name when the player was in the background. In the interim, I enabled the Spotify connector at Last.fm so the scrobbling is working without the extension, but no pop-ups. Not sure if this helps.
> 
> [Last.Fm Application Connector](https://www.last.fm/settings/applications)

Ya those connectors don't scrobble when playing music through another device

**Comment by dubeyy** [comment] 2020-02-28 22:45
I just tried downloading the LastFM desktop client and it scrobbles these PC->Sonos plays. I could have swore it didn't in the past. Must have lost hundreds of plays but there we go..

**Closed** 2020-02-29 08:03 UTC
Labels: bug, can't reproduce

**Comment by alexesprit** [comment] 2020-02-29 08:14
I updated Spotify connector to ignore other tabs only (when "Web Playing" is playing). It should resolve both this issue and #2242.
