### ISSUE TITLE
Music played through URLs of the type https://www.xiami.com/radio/play/ while supported by Web Scrobbler isn't scrobbled.

### ISSUE THREAD

**Issue by NomaanMalick** [web-scrobbler/web-scrobbler#1909] opened 2019-02-10 13:12 UTC
### Steps to reproduce (for bugs)

1\.
2\.
3\.

### Steps for resolving the issue

-   [ ] Reauthenticate on Last.fm
    
    
    
-   [ ] Try to use unpacked extension from latest master
    
    
-   [ ] Check other issues for duplicates

### Environment

-   Version used:
-   Browser name and version:

**Comment by alexesprit** [comment] 2019-06-12 11:59
Looks like it's a duplicate of #1817.

**Closed by alexesprit** 2019-06-12 11:59 UTC
Labels: bug, connector
