### ISSUE TITLE
Edge Add-Ons Web Scrobbler way out of date compared to Chrome

### ISSUE THREAD

**Issue by jivison** [web-scrobbler/web-scrobbler#3480] opened 2022-11-19 03:03 UTC
The Web Scrobbler extension in the Edge Add-Ons store is at 2.50.2, while the Chrome Web Store version is at 2.81.0.

Is there a reason it's so out of date? I had to switch to the Web Store version to get the latest version to fix YouTube Music scrobbling.

Links:
https://microsoftedge.microsoft.com/addons/detail/web-scrobbler/obiekdelmkmlgnhddmmnpnfhngejbnnc
https://chrome.google.com/webstore/detail/web-scrobbler/hhinaapppaileiechjoiifaancjggfjm

Edit: I'm on Mac v. 12.5.1, not sure if that makes a difference or not

**Comment by yayuyokitano** [comment] 2022-11-19 07:02
Duplicate of #3357 
As a status update on that, credentials have been obtained for edge publishing as of a few days ago, but implementation remains

**Closed by yayuyokitano** 2022-11-19 07:02 UTC
