### ISSUE TITLE
Web Scrobbler NOT using Youtube Music to get track info

### ISSUE THREAD

**Issue by fourthpanda** [web-scrobbler/web-scrobbler#3842] opened 2023-06-03 09:15 UTC
**Describe the bug**
Playing a reuploaded track that isn't the origin of the song incorrectly pulls track info from the channel/video name instead of using the info that YouTube Music has recognized (when you hit expand below the video, and is the correct track info)

**How to reproduce**
1. Play a reupload of a track on YouTube
2. Verify YouTube music is recognizing the correct origin/original track under the video
3. Check what Web Scrobbler is actually scrobbling by clicking the extension
4. See incorrect track info

**Expected behavior**
Pull correct track info including Artist from YouTube Music so that platforms (like last.fm) can save it correctly in my track history and therefor correctly recommend related tracks and etc.

**Screenshots**
![image](https://github.com/web-scrobbler/web-scrobbler/assets/31490873/44c0ce6c-2dec-4f1d-b8c8-8d5d6fc6c50d)

**Environment**
-   OS: Windows 10
-   Browser: Chrome
-   Extension version: 3.0.10

**Additional context**
"Use Youtube Music to get track info" is checked within Web Scrobbler options (always has been)
Also I have already added @@||ws.audioscrobbler.com to my uBlock filters and I have no other extensions that are for YouTube.

**Comment by yayuyokitano** [comment] 2023-06-03 10:34
What you describe is not youtube music info, it is copyright info. This is not yet implemented, and there exists an issue for it. See #2742 

The youtube music information for this track is the same as the normal youtube title: see https://music.youtube.com/watch?v=xVJgBbvyTaw

Closing as duplicate of formerly mentioned issue

**Closed by yayuyokitano** 2023-06-03 10:34 UTC
Labels: bug
