### ISSUE TITLE
can't work on listen.moe

### ISSUE THREAD

**Issue by jqk4388** [web-scrobbler/web-scrobbler#1580] opened 2018-02-21 03:13 UTC
### Steps to reproduce (for bugs)

1.
2.
3.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used:
* Browser name and version:

 **can't work on https://listen.moe/**

**Comment by inverse** [comment] 2018-02-21 19:30
This should be fixed in the next release. A patch was already pushed.

**Comment by alexesprit** [comment] 2018-03-04 07:52
Closed as a duplicate of #1563.

**Closed by alexesprit** 2018-03-04 07:52 UTC
Labels: connector

**Comment by GintokiHub** [comment] 2018-08-03 18:51
Listen.moe scrobbles the tracks which are playing at that time on the radio. 
So far so good but it also scrobbles when you haven't got the 'play button' aka radio actually playing.
