### ISSUE TITLE
Spotify double or multiple artist for single track problem

### ISSUE THREAD

**Issue by flickur** [web-scrobbler/web-scrobbler#2721] opened 2021-01-27 14:19 UTC
So i've been using the scrobbler with youtube for years and now i've started using it for spotify too cause i got sick of spotify's all over the place tagging. There's only one problem i've noticed and that is when a song has multiple artists credited for it. With the built in scrobbling for Spotify it only uses the first artist for scrobbles, but with the web scrobbler it always includes them all in the format "Artist1, Artist2, etc" separated by comma which results in incorrect artist tag almost 100% of the time since artist collaborations are pretty much never in format like that.

Would it be possible to make the default behaviour be that it only takes the first artist (which should always be the main artist afaik) and scrobbled it like that. It would result in much more correct tags and we could always make custom edits when there's need to have multiple artist in the tags (with the correct format).

**Comment by alexesprit** [comment] 2021-01-27 14:28
Closed as a duplicate of #2588.

**Closed by alexesprit** 2021-01-27 14:28 UTC
Labels: duplicate
