### ISSUE TITLE
Add support to Nico Nico Douga

### ISSUE THREAD

**Issue by YanLobianchi** [web-scrobbler/web-scrobbler#2505] opened 2020-08-02 22:59 UTC
Nico Nico Douga is the most popular online video platform from Japan: https://www.nicovideo.jp/.
Some of music videos has the japanese bar character (／), the recognizer could identify this (if not yet).

**Comment by alexesprit** [comment] 2020-08-03 03:48
Closed as a duplicate of #1932.

**Closed by alexesprit** 2020-08-03 03:48 UTC
Labels: connector, request
