### ISSUE TITLE
[YouTube] Individual video overwrite

### ISSUE THREAD

**Issue by roobscoob** [web-scrobbler/web-scrobbler#3197] opened 2022-03-27 22:40 UTC
**Is your feature request related to a problem? Please describe.**
I disable scribbling on videos not tagged as "Music" because often it scrobbles non-music tracks, however once in a while a video I would want to be scrobbled is not tagged music and thus doesn't get scrobbled.

**Describe the solution you'd like**
WebScrobbler already lets you change the details (name, author, album, etc) of music tracks. It also lets you prevent videos from scrobbling. It would be good if it let you overwrite the inverse. Let me tag a video (that usually wouldn't get scrobbled) as one that _does_ get scrobbled with a specified name, author, album, etc.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yayuyokitano** [comment] 2022-03-27 22:47
Duplicate of #1769

**Closed by yayuyokitano** 2022-03-27 22:47 UTC
Labels: feature
