### ISSUE TITLE
Repeating songs only scrobbles once (youtube/spotify)

### ISSUE THREAD

**Issue by flickur** [web-scrobbler/web-scrobbler#2836] opened 2021-04-23 10:48 UTC
Songs are only scrobbled once when listening on repeat either on Spotify or Youtube (loop video).

**Comment by flickur** [comment] 2021-04-23 11:35
Seems like I can't reproduce it on youtube. Maybe it was a specific video or something cause it seems to be working now, weird. For spotify it still doesn't get scrobbled more than once.

**Comment by alexesprit** [comment] 2021-04-25 07:53
I've just enabled "Repeat One" and listened a song twice. The song was scrobbled twice, as expected.

**Comment by yayuyokitano** [comment] 2021-04-25 20:06
Can reproduce, but not reliably. I actually talked about something I think might be related in discord recently. I have experienced this a lot on eggs.mu, and very occasionally when repeating on youtube (i have an impression it happens more often when tabbed out but might just be me, i didn't measure). It seems completely random when it happens to me, and i rarely if ever see it failing twice in a row. That's all I know for now, but I have been looking into it a bit.

**Comment by flickur** [comment] 2021-04-25 21:16
It seems to be song-specific somehow. Some songs work for me but some don't. Like this doesn't for example:
https://open.spotify.com/album/6nvvOIQoyryvZjr7baMuXP

**Comment by alexesprit** [comment] 2021-04-28 15:17
Should be related to #2847. We use song duration to detect replays, and the extension does not get duration from the page. Perhaps, they changed the website layout recently.

**Comment by flickur** [comment] 2021-04-28 17:09
Aight so far every korean song has only been scrobbled once despite playing on repeat, but literally all non-kpop tracks have worked fine wth :D

**Comment by flickur** [comment] 2021-05-03 11:50
Okay now there's also case of double scrobbles during one listen. The scrobbler gets shorter duration probably and scrobbles the track two times in one listen. This song at least does that.

https://open.spotify.com/track/4wAHfAaREe5m3b2ED4f1ii?si=c113be12e1054a30

**Comment by falcononthesax** [comment] 2021-05-09 11:21
I've been having this problem too. It's mainly with specific songs though.

**Comment by alexesprit** [comment] 2021-05-17 15:11
Closed as a duplicate of #2847.

**Closed by alexesprit** 2021-05-17 15:11 UTC
Labels: bug, can't reproduce
