### ISSUE TITLE
Youtube not scrobblinf "music" category

### ISSUE THREAD

**Issue by Hast** [web-scrobbler/web-scrobbler#1807] opened 2018-11-16 12:45 UTC
YouTube scrobbling works just fine, if I uncheck both checkbox in "youtube categories" setting. But if I check "music" category, it doesn't scrobble, even though I'm listening to videos from music category. Maybe it has something to do with the translations and the plugin not parsing category for a non-english interface?

**Comment by matyasstrelec** [comment] 2018-11-17 18:08
yep, same for me

**Comment by inverse** [comment] 2018-11-17 20:12
Duplicate of #1779

**Comment by inverse** [comment] 2018-11-17 20:13
I think this is a duplicate of #1805

**Comment by inverse** [comment] 2018-11-17 20:29
Should be fixed in the latest release - just deployed.

**Closed** 2018-11-19 20:10 UTC
Labels: bug, connector
