### ISSUE TITLE
Last update on Microsoft Edge was on 2022 January

### ISSUE THREAD

**Issue by maxmillerb** [web-scrobbler/web-scrobbler#3502] opened 2022-12-04 19:49 UTC
Last update on Microsoft Edge was on 2022 January (version 2.50.2)

https://microsoftedge.microsoft.com/addons/detail/web-scrobbler/obiekdelmkmlgnhddmmnpnfhngejbnnc

**Comment by yayuyokitano** [comment] 2022-12-04 19:58
Closing as duplicate of #3357
#3493 will address this once completed

**Closed by yayuyokitano** 2022-12-04 19:58 UTC
Labels: bug
