### ISSUE TITLE
Web Scrobbler doesn't scobble from YouTube anymore in Firefox.

### ISSUE THREAD

**Issue by NomaanMalick** [web-scrobbler/web-scrobbler#1924] opened 2019-03-01 18:39 UTC
### Steps to reproduce (for bugs)

1\.
2\.
3\.

### Steps for resolving the issue

-   [ ] Reauthenticate on Last.fm
    
    
    
-   [ ] Try to use unpacked extension from latest master
    
    
-   [ ] Check other issues for duplicates

### Environment

-   Version used:
-   Browser name and version:

**Comment by inverse** [comment] 2019-03-05 17:42
Dupe of #1897

**Closed by inverse** 2019-03-05 17:42 UTC
