### ISSUE TITLE
Web Scrobbler is not working with Spotify, please help

### ISSUE THREAD

**Issue by Jean-Paul97** [web-scrobbler/web-scrobbler#4855] opened 2024-08-01 01:02 UTC
Web Scrobbler is not working with Spotify, please help.

**Comment by suzykpop** [comment] 2024-08-01 01:31
me too, plz help

**Comment by yayuyokitano** [comment] 2024-08-01 03:23
Duplicate of #4849 please see that issue for details and updates.

**Closed by yayuyokitano** 2024-08-01 03:23 UTC
Labels: bug
