### ISSUE TITLE
Bug to Scrobble deezer

### ISSUE THREAD

**Issue by MatF2F** [web-scrobbler/web-scrobbler#3350] opened 2022-09-06 08:50 UTC
web-scrobbler doesn't seem to always work well. I use firefox, but i test with chrome and it's the same.
First problem, it doesn't detect the st of the first track of an album but you go to the next track and back to the fist it work
Often, web-scrobbler dectect the change of track but not the data of the track and can scobble several time the data of the same track but same if you the next track and back to the fist it work

**Comment by Sherer420** [comment] 2022-09-06 10:49
Same problem. Chrome 105.0.5195.102

**Comment by mariomarinato** [comment] 2022-09-06 12:48
It's a duplicate of #3337

**Comment by sapphaos** [comment] 2022-09-11 09:02
Same, it started happening a few days ago

**Comment by inverse** [comment] 2022-10-01 20:14
Should be resolved

**Closed by inverse** 2022-10-01 20:14 UTC
Labels: bug
