### ISSUE TITLE
web scrobbler suddenly unable to scrobble youtube

### ISSUE THREAD

**Issue by i-dont-exsist-3** [web-scrobbler/web-scrobbler#2674] opened 2020-12-18 11:51 UTC
a couple days sago the web scrobbler began refusing to scrobble music on youtube (and spotify web player), being either greyed out or solid red.
[logs of the background script.txt](https://github.com/web-scrobbler/web-scrobbler/files/5715436/logs.of.the.background.script.txt)
[logs of content scripts.txt](https://github.com/web-scrobbler/web-scrobbler/files/5715437/logs.of.content.scripts.txt)

**Comment by alexesprit** [comment] 2020-12-18 11:53
Closed as a duplicate of #2667.

https://twitter.com/web_scrobbler/status/1339625550000885762?s=20

**Closed by alexesprit** 2020-12-18 11:53 UTC
