### ISSUE TITLE
Customizeable "Submission" Timer

### ISSUE THREAD

**Issue by nuclear** [web-scrobbler/web-scrobbler#2015] opened 2019-07-17 12:08 UTC
IIRC the plugin currently sends the data to last.fm at 4:00

It would be nice if we could define custom values, absolutes (time) and relatives (% of the video)
Also, free last.fm users cannot edit already submitted scrobbels, therefore an option to wait for a confirmation could be helpful

**Comment by alexesprit** [comment] 2019-07-17 12:32
Closed as a duplicate of #453.

**Closed by alexesprit** 2019-07-17 12:32 UTC
Labels: duplicate
