### ISSUE TITLE
Scrobbling doesnt work on Youtube Music

### ISSUE THREAD

**Issue by Juliasmatius** [web-scrobbler/web-scrobbler#4710] opened 2024-05-14 23:37 UTC
**Describe the bug**
When playing music on Youtube Music, extension will not detect playing music.
**How to reproduce**
1. Play song on Youtube Music
2. Open extension popup

**Expected behavior**
The extension should have deetected the currently playing song and sent it off to connected accounts.

**Screenshots**
![image](https://github.com/web-scrobbler/web-scrobbler/assets/80146546/796c31d5-272b-48fc-be1e-66ed5b792afb)

**Debug logs**
[https://pastebin.com/RaqHDFhP](https://pastebin.com/RaqHDFhP)
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: Arch Linux
-   Browser: Firefox
-   Extension version: 3.7.0
**Additional context**

**Comment by inverse** [comment] 2024-05-15 17:34
Perhaps this change should fix it that's in the next unpublished release https://github.com/web-scrobbler/web-scrobbler/pull/4587

**Comment by inverse** [comment] 2024-05-15 17:50
Actually looks like a duplicate of #4613 closing in favour of that one.

**Closed by inverse** 2024-05-15 17:50 UTC
Labels: bug, connector
