### ISSUE TITLE
Spotify Connector not working

### ISSUE THREAD

**Issue by babyufo** [web-scrobbler/web-scrobbler#3749] opened 2023-05-24 12:25 UTC
Describe the bug:
Spotify stopped scrobbling

How to reproduce:

Go to Spotify
Click on Music Box Dancer by Frank Mills
Expected behavior
Scrobbling (aka the Red icon turning green)

Environment (please complete the following information)

OS: (e.g. Windows, Mac)
Windows
Browser: (e.g. Chrome, Safari)
Brave
Extension version: (e.g. V2.89.0)

**Comment by yayuyokitano** [comment] 2023-05-24 16:43
I've created PR #3751 that addresses this.
Unfortunately, in a bout of absolutely terrible timing, we are in the middle of pushing a very big update right now, so it might take us a little more time than usual to actually get this fix pushed, but we will do our best to make this quick.

**Comment by 0edit** [comment] 2023-05-25 02:35
Came here to report the same issue. Only difference is I'm on Chrome.

**Comment by tiffanyami** [comment] 2023-05-25 03:24
I got the same issue. Tried installing the extension again and again but didn't work. the icon kept red when music was playing. Issue occurs in all my Chrome, Opera, and Firefox. The bug seems to be with spotify connector, I tried connecting to youtube and eveything was ok.

**Comment by inverse** [comment] 2023-05-25 06:44
Fix is on master we just need to do a new release - it'll be a major release change with lots of new features + visual style change.

**Comment by lpthao03** [comment] 2023-05-27 02:34
Describe the bug: WEB SCROBBLER NOT WORKING WHEN USING SPOTIFY
Expected behavior: when I play music on Spotify it will be charged to web scrobbler corresponding to my linked lastfm account.
![image](https://github.com/web-scrobbler/web-scrobbler/assets/119160911/ed17da37-ca73-45c5-80c5-fbe92ae386f0)
Environment : Windows - Chrome,
Additional context : I tried it on another website like youtube it works fine, but spotify doesn't.
![image](https://github.com/web-scrobbler/web-scrobbler/assets/119160911/da1a4341-585d-4f93-a8b4-5c54b9e4ccf3)

**Comment by yayuyokitano** [comment] 2023-05-27 08:26
Update: Web Scrobbler V3 has been uploaded to all platforms. We now wait for the platforms to review the extension and hopefully approve it.
For the time being, this is completely out of our hands.

**Comment by yayuyokitano** [comment] 2023-05-27 14:03
Accepted to chrome web store, since the vast majority of our users are there I am marking this as solved.
Keeping issue pinned until out on AMO as well.

**Closed by yayuyokitano** 2023-05-27 14:03 UTC
Labels: bug

**Comment by missp001** [comment] 2023-05-27 16:31
Hello, the scrobbler still does not work on Spotify.
![spotify scrobbler](https://github.com/web-scrobbler/web-scrobbler/assets/134798869/76e05dc7-0e1c-4ce6-908c-33cfad2f7232)

It does work on YT.
![YT scrobbler2](https://github.com/web-scrobbler/web-scrobbler/assets/134798869/d9398cb0-8d08-443a-a9cc-7a7d9898279c)

**Comment by gigithegigiki** [comment] 2023-05-27 21:18
I hope you will fix it soon (the spotify problem).
BUT the new version seems it consumes memory... AND **I PREFER THE OLDER ONE...** the new style is **bad** and it takes **long time** to open and edit the information....

**Comment by missp001** [comment] 2023-05-28 04:17
Thank you! Spotify connector fixed on Chrome and others (Brave, Vivalde, Opera) browsers.

However, it still doesn't scrobble in Firefox and Edge. The scrobbler icon stays in red. Tried logging in and out on both lastfm and Spotify. Any suggestions?

On Mozilla Firefox
![firefox web scrobbler 1](https://github.com/web-scrobbler/web-scrobbler/assets/134798869/b6adba3a-65e1-45e3-8549-da7cd47a485a)
![firefox web scrobbler 2](https://github.com/web-scrobbler/web-scrobbler/assets/134798869/ec21e31c-c753-481b-825a-0953a3e24022)

On Microsoft Edge
![edge 1](https://github.com/web-scrobbler/web-scrobbler/assets/134798869/8e040b27-41a8-4c03-9ce5-cde9713eb051)
![edge 2](https://github.com/web-scrobbler/web-scrobbler/assets/134798869/134ba1da-06fe-408e-953b-c7829cbf2874)

**Comment by rgoudie** [comment] 2023-05-28 04:56
The icon has changed, but your screenshots still display the old icon. This leads me to believe that your Firefox browser perhaps did not automatically update the WebScrobbler. Can you try doing that manually?

    On Saturday, May 27, 2023 at 09:17:54 p.m. PDT, missp001 ***@***.***> wrote:  Thank you! Spotify connector fixed on Chrome and others (Brave, Vivalde, Opera) browsers.
However, it still doesn't scrobble in Firefox and Edge. The scrobbler icon stays in red. Tried logging in and out on both lastfm and Spotify. Any suggestions?

**Comment by yayuyokitano** [comment] 2023-05-28 06:27
Yes, as rgoudie points out, you are still on the old version. Mozilla and Microsoft have not yet accepted version 3 to their marketplaces. Unfortunately there is nothing we can do on our side except wait for them to accept it.

**Comment by missp001** [comment] 2023-05-28 06:28
> The icon has changed, but your screenshots still display the old icon. This leads me to believe that your Firefox browser perhaps did not automatically update the WebScrobbler. Can you try doing that manually?

Yes. Thought of that too cos in Chrome and Opera, the icons has changed. So I checked if web scrobbler has been updated, and it seems to be updated and/or no updates found. Browser is also updated.


![firefox web scrobbler 3](https://github.com/web-scrobbler/web-scrobbler/assets/134798869/3925230e-cb27-4e1f-a6e2-7617e060111f)
![firefox web scrobbler 7](https://github.com/web-scrobbler/web-scrobbler/assets/134798869/ec813de1-8369-4633-9b31-9990b4c4a6d2)
![firefox web scrobbler 6](https://github.com/web-scrobbler/web-scrobbler/assets/134798869/24efcd27-dcf2-49e9-8351-d4601c69652b)

**Comment by missp001** [comment] 2023-05-28 06:30
> Yes, as rgoudie points out, you are still on the old version. Mozilla and Microsoft have not yet accepted version 3 to their marketplaces. Unfortunately there is nothing we can do on our side except wait for them to accept it.

Oh okay. I will wait then. Thank you.

**Comment by yayuyokitano** [comment] 2023-05-28 06:35
> I hope you will fix it soon (the spotify problem). BUT the new version seems it consumes memory... AND **I PREFER THE OLDER ONE...** the new style is **bad** and it takes **long time** to open and edit the information....

This is not really the place for this, but to answer a little bit, V3 came into being because chrome made it so that the old way the extension worked would soon become impossible to get approved to chrome and edge marketplaces, leading to us needing to rewrite a significant portion of the codebase. The fresh code is currently less optimized than the previous code that has been tried and tested for several years, but it is also easier to work with and fix in the future. Once we get through some of the major bugs in the release we plan to look more closely at the performance, to get rid of a little of the lag. I will not be responding further than that here, though you can open a thread in Discussions if you want to talk more details.

**Comment by gigithegigiki** [comment] 2023-05-28 06:41
> V3 came into being because chrome made it so that the old way the extension worked would soon become impossible to get approved to chrome and edge marketplaces, leading to us needing to rewrite a significant portion of the codebase. The fresh code is currently **less optimized** than the previous code that has been tried and tested for several years, but it is also easier to work with and fix in the future. Once we get through some of the major bugs in the release we plan to look more closely at the performance, to get rid of a little of the lag.

Thanks for your reply, just focus in this lag in response and that it consumes memory and CPU even when it doesn't scrobble...

**Comment by GreenYuran** [comment] 2023-05-28 08:34
Thanks for this handy addon.
 Same problem as many.  I cleaned the browser to zero, I already wanted to reinstall it, but decided to drop by the developers just in case. And here is some good news! Oh, looking forward to the release of the third version!

**Comment by gigithegigiki** [comment] 2023-05-31 07:11
the version **3.0.10** again doesn't scrobble  Spotify

**Comment by yayuyokitano** [comment] 2023-05-31 09:38
> the version **3.0.10** again doesn't scrobble Spotify

Can't reproduce this. What does the extension popup say when you try to scrobble? Is it happening reliably, or just sometimes?

**Comment by f0244** [comment] 2023-05-31 14:49
Confirming the 3.0.10 not scrobbling for Spotify in Chrome. The popup has the "Play some music to get started
Is it already playing?" message.

**Comment by RAM237** [comment] 2023-05-31 15:03
v3.0.10 works for me with Spotify

**Comment by rgoudie** [comment] 2023-05-31 15:42
I have version 3.0.10 installed. I can confirm that I am able to scrobble.

    On Wednesday, May 31, 2023 at 08:03:13 a.m. PDT, Pavel ***@***.***> wrote:  v3.0.10 works for me with Spotify
