### ISSUE TITLE
Incorrect album scrobbling on YouTube Music

### ISSUE THREAD

**Issue by bestfiction** [web-scrobbler/web-scrobbler#2695] opened 2021-01-03 11:49 UTC
**Describe the bug**
When playing an album, Web Scrobbler scrobbles all the tracks with the title of the first track you play.
E. g. if you play Lana Del Rey's album "NFR!" starting with the song "Mariners Apartment Complex", it will scrobble every subsequent song as "Mariners Apartment Complex".

**How to reproduce**
Open Youtube Music app
Start playing any album
Wait until the second track starts playing
Check your scrobbles, it will scrobble the second track with the title of the first.

**Expected behavior**
Expected the tracks to scrobble with the correct titles.

**Screenshots**
https://i.imgur.com/gTqQUr3.png

**Debug logs**
https://pastebin.com/T7ZwjNBd

**Environment (please complete the following information)**
Windows, Chrome (using separate YT Music app), v. 2.39.2

**Comment by alexesprit** [comment] 2021-01-03 11:53
I guess it's a duplicate of #2677.

**Closed by alexesprit** 2021-01-03 11:53 UTC
Labels: bug

**Comment by alexesprit** [comment] 2021-01-03 11:56
If you want to help to resolve the issue, check my comment: https://github.com/web-scrobbler/web-scrobbler/issues/2677#issuecomment-753606016 :)
