### ISSUE TITLE
simple <embedded YouTube-player > not scrobbling

### ISSUE THREAD

**Issue by Timmaaaa** [web-scrobbler/web-scrobbler#2260] opened 2020-02-11 13:22 UTC
website is using an embedded Youtube Player;
(title n artist is also in control-button-bar;)
URL: https://treesradio.com/
demo-acc: not needed (YT-vids are constantly playing);

solving this issue would make my heart<3 light up 
combined w/ a friendly student-donation haha;

**Comment by Timmaaaa** [comment] 2020-02-11 13:31
![grafik](https://user-images.githubusercontent.com/21161510/74240849-0d207080-4cdb-11ea-97b5-6b5f72762bae.png)
there is the embedded _playing_ -youtube-link & the title of the current video c:

**Comment by alexesprit** [comment] 2020-02-11 14:41
Closed as a duplicate of #2260.

**Closed by alexesprit** 2020-02-11 14:41 UTC
Labels: connector, request

**Comment by Timmaaaa** [comment] 2020-02-11 15:35
@alexesprit  in #1653 there is no help whatsoever.. I added pictures and text to help... (Couldn't the older one be closen?)
