### ISSUE TITLE
activate button in all tabs [enhancement]

### ISSUE THREAD

**Issue by martouss** [web-scrobbler/web-scrobbler#2265] opened 2020-02-15 15:20 UTC
As most of the users listen to music just in just one tab at a single time, I think it's a good idea to activate the extension button in all tab (even tabs which don't play any music) so users can edit tracks or love them from each tab.

**Comment by alexesprit** [comment] 2020-02-15 16:42
Duplicate of #1581.

**Closed by alexesprit** 2020-02-15 16:42 UTC
Labels: duplicate
