### ISSUE TITLE
youtube not scrobbling

### ISSUE THREAD

**Issue by bulletchained** [web-scrobbler/web-scrobbler#2670] opened 2020-12-17 20:37 UTC
youtube does not scrobble for me, says "play some music to get started" and will not recognize anything, tried things that previously scrobbled. i tried disabling + reenabling youtube connector, restarting chrome and reinstalling the extension and still not working. 

windows 10 x64
web scrobbler vers 2.39.0
google chrome vers 87.0.4280.88 

debug: https://pastebin.com/JEJAfc2C

i see the error in debug "no scrobblers are bound" but not sure how to fix that, it did not show any issue when i was logging in to lastfm after reinstalling 

![image](https://user-images.githubusercontent.com/76183275/102540898-b5caf980-407d-11eb-9d09-8abdfbd44fb4.png)

also it does it for every video but here's a random one that definitely scrobbled before that wont now https://www.youtube.com/watch?v=emqW_3ZxAy4

**Comment by bulletchained** [comment] 2020-12-17 20:39
also it does it on every video but heres a random one that definitely scrobbled before that wont now, but its the same for any https://www.youtube.com/watch?v=emqW_3ZxAy4

**Comment by inverse** [comment] 2020-12-17 20:42
Could be related to #2669

**Comment by lauram-h** [comment] 2020-12-17 20:57
Youtube is also not scrobbling for me, with the same error as above.
Ubuntu 20.04.1 LTS
Chrome Version 87.0.4280.88 (Official Build) (64-bit)
Pastebin of the logs: https://pastebin.com/aWaXpAP0

Like the above, it's not video-specific; everything for the past 2 hours, including things that have been scrobbled before, have failed.

**Comment by bulletchained** [comment] 2020-12-17 20:58
yeah my last scrobbles are from 15 hours ago so it started some time between then and now for me

**Comment by dreman6** [comment] 2020-12-17 21:34
yeah it hasnt scrobbled youtube from me for a while either.

**Comment by saturnz11** [comment] 2020-12-18 00:32
in microsoft edge didn't scrobble neither. yesterday i tried reinstalling and it worked, but now, today, it stopped working again

**Comment by alexesprit** [comment] 2020-12-18 06:22
Closed as a duplicate of #2667.

https://twitter.com/web_scrobbler/status/1339625550000885762?s=20

**Closed by alexesprit** 2020-12-18 06:22 UTC
Labels: bug
