### ISSUE TITLE
Force a specific connector in websites of a different domain with same frontend

### ISSUE THREAD

**Issue by mfachal** [web-scrobbler/web-scrobbler#2709] opened 2021-01-13 19:47 UTC
**Is your feature request related to a problem? Please describe.**
Some artists connect their domain to connected websites directly. For example, sewerslvt.com exposes the frontend for bandcamp, and going to the bandcamp subdomain redirects to sewerslvt.com.

**Describe the solution you'd like**
Being able to force a certain detector for the website, probably on the menu.

**Describe alternatives you've considered**
Currently an idea is to scrobble manually on last.fm, or go to another website that mirrors the artist's music

**Additional context**
As described above.

**Comment by alexesprit** [comment] 2021-01-14 07:25
Closed as a duplicate of #1882.

There's also a manual way to force scrobbling from custom domains via using custom URL patterns: https://github.com/web-scrobbler/web-scrobbler/wiki/Custom-URL-patterns.

**Closed by alexesprit** 2021-01-14 07:25 UTC
Labels: feature
