### ISSUE TITLE
Primephonic connector broken on MS Edge

### ISSUE THREAD

**Issue by Martin-UK** [web-scrobbler/web-scrobbler#2703] opened 2021-01-08 12:54 UTC
Web-scrobbler on MS Edge recently stopped working for Primephonic streaming music service at https://play.primephonic.com/

-   OS: Windows 10 build 19042.685
-   Browser: MS Edge  v87.0.664.75 
-   Extension version: 2.39.2
-   Error message: Red icon, "Play some music to get started...Is it already playing?"
-   Example stream: https://play.primephonic.com/album/7318599924458

Primephonic connector seems OK for other browsers, e.g. Google Chrome.

**Comment by alexesprit** [comment] 2021-01-08 12:57
Closed as a duplicate of #2688.

**Closed by alexesprit** 2021-01-08 12:57 UTC

**Comment by alexesprit** [comment] 2021-01-08 13:49
I submitted v2.40.0 where this issue was fixed. It will be available on MS Edge Addons once it's approved.
