### ISSUE TITLE
Accesses Data on All Sites

### ISSUE THREAD

**Issue by toddgrotenhuis** [web-scrobbler/web-scrobbler#2462] opened 2020-06-26 13:26 UTC
**Describe the bug**
Site only needs permissions for the sites it is working with (e.g. the music streaming sites and the scrobbling sites), but asks for access to all browsing data.

**How to reproduce**
1. Go to https://addons.mozilla.org/en-US/firefox/addon/web-scrobbler/
2. Click on 'Add to Firefox'
3. See error

**Expected behavior**
Extension requests permission only for sites that it uses as streams or scrobbling.

**Screenshots**
<img width="283" alt="image" src="https://user-images.githubusercontent.com/165077/85862047-3f64d300-b78f-11ea-826c-0077162c77aa.png">

**Comment by alexesprit** [comment] 2020-06-26 14:58
Why is this an issue? The reason why the extension asks to access to all websites is explained in privacy policy.

https://github.com/web-scrobbler/web-scrobbler/blob/master/src/_locales/en/privacy.md

**Comment by alexesprit** [comment] 2020-06-26 15:05
Also see https://github.com/web-scrobbler/web-scrobbler/issues/440#issuecomment-53183324 for details.

**Comment by alexesprit** [comment] 2020-07-12 20:31
I'm closing this issue as a duplicate of #440.

**Closed** 2020-07-13 04:55 UTC
Labels: non-issue
