### ISSUE TITLE
Youtube not scrobbling

### ISSUE THREAD

**Issue by domdod88** [web-scrobbler/web-scrobbler#2673] opened 2020-12-18 08:04 UTC
Youtube will not scrobble under any circumstance

**Comment by drymar** [comment] 2020-12-18 08:59
Yeah, youtube just started to be not unrecognizable.

**Comment by alexesprit** [comment] 2020-12-18 09:25
Closed as a duplicate of #2667.

https://twitter.com/web_scrobbler/status/1339625550000885762?s=20

**Closed by alexesprit** 2020-12-18 09:25 UTC
Labels: bug
