### ISSUE TITLE
spotify scrobbling on firefox doesn't work

### ISSUE THREAD

**Issue by redbird6** [web-scrobbler/web-scrobbler#3580] opened 2023-02-16 14:52 UTC
like the title says it, it just doesn't work. it worked perfectly fine like 2 days ago but it just doesn't anymore. i checked everything to make sure i'm not wrong: reinstalled the extension, turned it on and off, logged in and out, but still no.

**Comment by yayuyokitano** [comment] 2023-02-16 15:06
Duplicate of #3576 
This is already solved, but the most recent update is pending approval from mozillas end
There is nothing we can do except wait, unfortunately

**Closed by yayuyokitano** 2023-02-16 15:06 UTC
Labels: bug
