### ISSUE TITLE
music.apple.com not identified on Edge

### ISSUE THREAD

**Issue by xmanoel** [web-scrobbler/web-scrobbler#3487] opened 2022-11-22 09:57 UTC
**Describe the bug**
The webscrobbler is not longer recognising my songs on AppleMusic on Edge. (On Chrome it works). 
Some changes may have happened on music.apple.com because it was working until now. 

**How to reproduce**
1. Open Edge
2. Log in Apple Music web
3. Reproduce Songs 
4. Web Scrobbler does not identify any playing son. 

**Expected behavior**
WebScrobbler turned into green and displayed the information of the Song. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1638222/203282730-c9617c76-f614-4f21-9e49-89fa0aaa745a.png)

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.
[music.apple.com-1669110901215.log](https://github.com/web-scrobbler/web-scrobbler/files/10066202/music.apple.com-1669110901215.log)

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Edge 
-   Extension version: 2.50.2

**Comment by yayuyokitano** [comment] 2022-11-26 09:36
Closing as a duplicate of #3357

For now, you can install the chrome version on edge as a temporary workaround, while edge publishing is set back up.
Ideally we will have the edge version back up to date soon, but I have no ETA.

**Closed by yayuyokitano** 2022-11-26 09:36 UTC
Labels: bug

**Comment by xmanoel** [comment] 2022-11-27 17:59
Thanks for the WA! Currently using the Chrome version on Edge. Works fine.
