### ISSUE TITLE
Batch scrobble editing and delayed scrobble submission

### ISSUE THREAD

**Issue by CodeHarmony64** [web-scrobbler/web-scrobbler#1834] opened 2018-12-15 14:41 UTC
### Expected behavior
I don't want to keep editinig the scrobbles being submitted for every song. Sometimes you are listening the music but aren't near to your computer, so hear It will keep scrobbling songs with unedited wrong data. I should be able to review all the scrobbles and then batch edit and submit at once

### Current behavior

It will keep submitting unedited scrobbles.

### Possible solution

Provide an option to delay the scrobbling.
Locally store all the songs which have been played but not yet scrobbled
Allow editing the info for individual tracks
Provide submit now button for scrobbles.

### Context

I play Indian music on youtube mostly from T-Series label eg. https://www.youtube.com/watch?v=rkWJyMhIWLo
Now the Scrobbled title was 
"Dekhte Dekhte Full Song | Batti Gul Meter Chalu | Atif Aslam | Shahid K Shraddha K | Nusrat Saab"
Though the details should be
Title : Dekhte Dekhte
Album : Batti Gul Meter Chalu
Singer : Atif Aslam

**Comment by alexesprit** [comment] 2019-05-21 06:28
Closed as a duplicate of #291.

**Closed** 2019-05-21 06:32 UTC
Labels: core, feature
