### ISSUE TITLE
Don't scrobble songs, if another source (e.g. a tab, or an app) is playing music

### ISSUE THREAD

**Issue by CennoxX** [web-scrobbler/web-scrobbler#2728] opened 2021-02-03 10:38 UTC
Web Scrobbler has a feature to not scrobble songs, if another source (e.g. a tab, or an app) is playing music on Spotify (originally implemented here: https://github.com/web-scrobbler/web-scrobbler/commit/7b3035b222386855eb80cd76ee8b6883684e2a19). With the redesign of Spotify the Connectbar doesn't have the css-class "qualaroo--connect-bar-visible" so the following code 
```
function hasMultipleSources() {
	return document.body.classList.contains('qualaroo--connect-bar-visible');
}
```
inside the [spotify connector](https://github.com/web-scrobbler/web-scrobbler/blob/master/src/connectors/spotify.js) doesn't work anymore and therefore scrobbles are again duplicated.

**Environment**
-   OS: Windows
-   Browser: Firefox 85.0 (64-Bit) 
-   Extension version: 2.40.0

**Comment by alexesprit** [comment] 2021-02-03 12:18
Duplicate of #2723.

I've already fixed this bug. Will submit a patch release today.

**Closed** 2021-02-03 18:35 UTC
Labels: duplicate
