### ISSUE TITLE
the bot is not working

### ISSUE THREAD

**Issue by tomatovitamin** [web-scrobbler/web-scrobbler#3019] opened 2021-10-13 18:40 UTC
I already uninstalled and installed the bot several times in my firefox and nothing came of it, what's happening?

**Comment by CennoxX** [comment] 2021-10-15 07:13
There is no bot in this project. What exactly is the problem, does the scrobbling only for spotify not work? If so, this a duplicate of #3020.

**Closed** 2021-10-15 18:47 UTC
