### ISSUE TITLE
Addon doesn't work with Amazon stations after the update

### ISSUE THREAD

**Issue by rahonejm** [web-scrobbler/web-scrobbler#2604] opened 2020-10-20 16:53 UTC
I went to Amazon Music today and it seems to have been updated. The new UI is much worse than before, but that's a talk for another time. The problem is the addon doesn't recognize the songs being played in stations anymore. Well, it does. But only the first song. After that, it says the "track isn't recognized". Reloading the page gets the addon to recognize the song again, but only until the next one starts. It worked perfectly as recently as yesterday, before I got hit by the update. Playing songs from anything that isn't a station (playlists, artists, albums) seems to work fine.

**Comment by inverse** [comment] 2020-10-20 19:05
Hi @rahonejm 

What amazon music site are you on? For me it's working on .de

![Uploading image.png…]()

**Comment by rahonejm** [comment] 2020-10-20 19:44
> 
> 
> Hi @rahonejm
> 
> What amazon music site are you on? For me it's working on .de
> 
> ![image](https://user-images.githubusercontent.com/713525/96632470-0c36e880-1318-11eb-8f3e-11f6c11c0413.png)
Before the update, the site looked like the one in your image and it worked fine. Now it looks like this (in Brazil):
![amazon 2](https://user-images.githubusercontent.com/36547869/96636198-53f74900-12f3-11eb-80ae-7823299b6fca.png)
![amazon](https://user-images.githubusercontent.com/36547869/96636201-55287600-12f3-11eb-83f7-2f299a0187bd.png)

And, as you can see, the addon seems to have been broken in the process.

**Comment by inverse** [comment] 2020-10-20 20:09
Ouch - yes that's def a massive overhaul.

Unfortunately I don't see it on the .de version.

We will have to wait for it to be rolled out here unless you or someone else has it and feels confident with making the modifications to support both layouts.

**Comment by rahonejm** [comment] 2020-10-21 03:46
Well, I'm not good at coding so giving feedback is probably the best I can do. Since this [reddit post](https://www.reddit.com/r/AmazonMusic/comments/jci83v/do_not_upgrade_the_desktop_client_to_80_large/) is 4 days old and I got the update just today, it seems they're slowly rolling it across the world. What a terrible update, let me tell you.

**Comment by inverse** [comment] 2020-10-27 20:21
Still no update in Germany :(

**Comment by rahonejm** [comment] 2020-10-27 22:33
Ha, lucky you. Hopefully it never gets there.

**Comment by alexesprit** [comment] 2020-10-28 06:04
> Before the update, the site looked like the one in your image and it worked fine. Now it looks like this (in Brazil):

Hmm, looks like it can be fixed w/o accessing to Amazon (I have no access due to geolocation). The only thing is we can't publish the update to Addons.mozilla.org, so you'll have to install it manually.

**Comment by alexesprit** [comment] 2020-10-28 06:15
@rahonejm You could also help to fix the issue by providing the outer HTML of the Amazon player bar. You can use the instruction from my comment: https://github.com/web-scrobbler/web-scrobbler/issues/2318#issuecomment-636291171.

**Comment by hans-juergen** [comment] 2020-10-28 07:23
OK, here is a screenshot from a German user (me) playing his uploaded MP3 album:

![Amazon Music Web Scrobbler working with uploaded MP3 album](https://user-images.githubusercontent.com/4970867/97404706-cd47fa80-18f6-11eb-9347-e08fc951d0e9.png)

I also see the new home page that @rahonejm has, I'll try to check a station with it now.

**Comment by alexesprit** [comment] 2020-10-28 08:18
> The problem is the addon doesn't recognize the songs being played in stations anymore. Well, it does. But only the first song. After that, it says the "track isn't recognized".

@rahonejm Could you also post two screenshots? 1) When the first song is playing; 2) When the second song is playing.

**Comment by rahonejm** [comment] 2020-10-29 00:42
First song:
![wwe](https://user-images.githubusercontent.com/36547869/97511562-1e430780-1966-11eb-8ab2-8df72ee359dc.png)

Second song:
![waw2](https://user-images.githubusercontent.com/36547869/97511563-1f743480-1966-11eb-8ae2-70346079fbf2.png)

HTLM code:
<div class="BAibzabUKijQgULVQbqCf false    false"><div class="_333T0bVoft6GGOqUYjsnIA" id="transport"><div class="_3l2xsX5-KkYUgDHJDu-L0r box"><music-horizontal-item icon-name="maximize" button-variant="primary" class=" hydrated" show-action-button="" image-src="https://m.media-amazon.com/images/I/6169o8k5ajL._CR0,0,497,497_UL256_.jpg" primary-text="You've Got Another Thing Coming" secondary-text="Judas Priest" primary-href="#" secondary-href-2="#"></music-horizontal-item><div class="p47IPNpQmNWfLLuJOgQJd box"><div class="_1O7Nz6NG97pViSwqCjjjmR"><music-button slot="buttons" size="small" icon-only="" icon-name="add" title="Add to My Music" aria-label="Add to My Music" tabindex="-1" role="button" variant="primary" refinement="none" class="hydrated"></music-button></div><div class="MEymoQvQLasR_V_wKwVuC"><music-button tabindex="0" icon-name="more" icon-only="" size="small" role="button" variant="primary" refinement="none" class="hydrated"></music-button></div></div></div><div class="_2EZickYBrNGgbqeaZ5l5hr box"><music-button aria-label="Thumbs Down" icon-name="dislike" icon-only="" size="small" role="button" tabindex="0" variant="primary" refinement="none" class="hydrated"></music-button><div style="display: none;"></div><music-button aria-label="Previous" class="hydrated sc-music-button-h" icon-name="previous" icon-only="" size="small" role="button" tabindex="0" variant="primary" refinement="none">Previous</music-button><music-button icon-name="pause" icon-only="" size="medium" role="button" tabindex="0" variant="glass" refinement="none" class="hydrated" aria-label="Pause"></music-button><music-button aria-label="Next" class="hydrated sc-music-button-h" icon-name="next" icon-only="" size="small" role="button" tabindex="0" variant="primary" refinement="none">Next</music-button><div style="display: none;"></div><music-button aria-label="Thumbs Up" icon-name="like" icon-only="" size="small" role="button" tabindex="0" variant="primary" refinement="none" class="hydrated"></music-button></div><div class="Xx52FQw07yLGieFL37mbk box"><div class="_1Ei4aEvn9gofJPl3s0mipM"><div class="_2VTMowi3azd5Canl6KHa_V"><music-button id="volume-button" icon-only="" icon-name="volumeon" size="small" role="button" tabindex="0" variant="primary" refinement="none" class="hydrated"></music-button></div></div><div class="DtpU5jkkI_iN0NO9vExpI"><music-button id="play-queue-button" icon-only="" icon-name="playqueue" size="small" role="button" disabled="" aria-disabled="true" tabindex="-1" variant="primary" refinement="none" class="hydrated"></music-button></div></div><div class="_1cn3f7nqjbSSnAU3ic9Ax4"><div class="_2kZX54kSefK6P6o3HZryN "><div class="_-6Qq1s2Oalqp7YPtVqbV8"></div><span class="_3yP3txtlF3CZD3uFxlQwRG"><div style="width: 90.5528%;" class="_1N5B6NeeW6y5MdyFLyRBK0"></div><div style="width: 14.8834%;" class="_3bsbRMXlVQ9k36KPzW56VX"></div></span><div class="_1zKYOZUYfxn3H_yDdDDbv _10uOAC2Muu5GBBlIsZ8exL"><div style="width: 14.8834%;" class="_1wBhwcHNPzcjR4_E0xNulC "><music-icon size="tiny" name="circle" variant="solid" class="hydrated"><span><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" version="1.1" viewBox="0 0 24 24"><g id="ic_other_circle" fill-rule="evenodd" stroke="none" stroke-width="1" fill="transparent"><rect id="//-Base" width="24" height="24" x="0" y="0" fill-opacity="0" fill-rule="nonzero"></rect><circle id="Combined-Shape" cx="12" cy="12" r="11" fill="#FFF" fill-rule="nonzero"></circle></g></svg></span></music-icon></div></div></div><div class="sXaGQzYs9WqImj2uxDCBs _1KQKoAP31YB14fDTsoEmwh"><span>0:46</span><span> - 4:23</span></div></div></div><div style="opacity: 0; height: 0px;" class="_2mKQbJpVMdkyLFzaW3DO0O" id="playqueue"><music-detail-header style="contain: layout; padding-top: 20px; display: block; margin-bottom: 0px;" class="_2FDIISbzwe91Uo9dchewUQ hydrated"></music-detail-header><header class="yhyY1ge6qyGDJkXpz3cXm"></header><b class="_1V25eLlQd3ub0OSIVdmx5U"><span class="_1gkWbSn9eWk-QuUOaViyiI"></span><span class="_2NzVbgnEe5bWJ7rpRV3H9n"></span></b><div class="_2FDIISbzwe91Uo9dchewUQ"></div><div class=""><div class="_3yhmPlrZ9kJ1NcTx4yoBLu"><div class="_1xpp05rcYIwWA_tv8t2Aac"><div aria-label="grid" aria-readonly="true" class="ReactVirtualized__Grid ReactVirtualized__List" role="grid" style="box-sizing: border-box; direction: ltr; height: auto; position: relative; width: 1496px; will-change: transform; overflow: auto;" tabindex="0"><div class="ReactVirtualized__Grid__innerScrollContainer" role="rowgroup" style="width: auto; height: 1600px; max-width: 1496px; max-height: 1600px; overflow: hidden; position: relative;"><music-image-row class="disabled-hover hydrated" role="row" tabindex="0" loading=""><!----><span class="index">1</span><span class="image disabled-hover"><music-image src="" size="56" class="hydrated"></music-image></span><div class="content"><div class="col1"><music-link role="link" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col2"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col3"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col4"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div></div></music-image-row><music-image-row class="disabled-hover hydrated" role="row" tabindex="0" loading=""><!----><span class="index">2</span><span class="image disabled-hover"><music-image src="" size="56" class="hydrated"></music-image></span><div class="content"><div class="col1"><music-link role="link" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col2"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col3"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col4"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div></div></music-image-row><music-image-row class="disabled-hover hydrated" role="row" tabindex="0" loading=""><!----><span class="index">3</span><span class="image disabled-hover"><music-image src="" size="56" class="hydrated"></music-image></span><div class="content"><div class="col1"><music-link role="link" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col2"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col3"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col4"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div></div></music-image-row><music-image-row class="disabled-hover hydrated" role="row" tabindex="0" loading=""><!----><span class="index">4</span><span class="image disabled-hover"><music-image src="" size="56" class="hydrated"></music-image></span><div class="content"><div class="col1"><music-link role="link" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col2"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col3"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col4"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div></div></music-image-row><music-image-row class="disabled-hover hydrated" role="row" tabindex="0" loading=""><!----><span class="index">5</span><span class="image disabled-hover"><music-image src="" size="56" class="hydrated"></music-image></span><div class="content"><div class="col1"><music-link role="link" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col2"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col3"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col4"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div></div></music-image-row><music-image-row class="disabled-hover hydrated" role="row" tabindex="0" loading=""><!----><span class="index">6</span><span class="image disabled-hover"><music-image src="" size="56" class="hydrated"></music-image></span><div class="content"><div class="col1"><music-link role="link" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col2"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col3"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col4"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div></div></music-image-row><music-image-row class="disabled-hover hydrated" role="row" tabindex="0" loading=""><!----><span class="index">7</span><span class="image disabled-hover"><music-image src="" size="56" class="hydrated"></music-image></span><div class="content"><div class="col1"><music-link role="link" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col2"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col3"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col4"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div></div></music-image-row><music-image-row class="disabled-hover hydrated" role="row" tabindex="0" loading=""><!----><span class="index">8</span><span class="image disabled-hover"><music-image src="" size="56" class="hydrated"></music-image></span><div class="content"><div class="col1"><music-link role="link" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col2"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col3"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col4"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div></div></music-image-row><music-image-row class="disabled-hover hydrated" role="row" tabindex="0" loading=""><!----><span class="index">9</span><span class="image disabled-hover"><music-image src="" size="56" class="hydrated"></music-image></span><div class="content"><div class="col1"><music-link role="link" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col2"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col3"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col4"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div></div></music-image-row><music-image-row class="disabled-hover hydrated" role="row" tabindex="0" loading=""><!----><span class="index">10</span><span class="image disabled-hover"><music-image src="" size="56" class="hydrated"></music-image></span><div class="content"><div class="col1"><music-link role="link" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col2"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col3"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col4"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div></div></music-image-row><music-image-row class="disabled-hover hydrated" role="row" tabindex="0" loading=""><!----><span class="index">11</span><span class="image disabled-hover"><music-image src="" size="56" class="hydrated"></music-image></span><div class="content"><div class="col1"><music-link role="link" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col2"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col3"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col4"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div></div></music-image-row><music-image-row class="disabled-hover hydrated" role="row" tabindex="0" loading=""><!----><span class="index">12</span><span class="image disabled-hover"><music-image src="" size="56" class="hydrated"></music-image></span><div class="content"><div class="col1"><music-link role="link" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col2"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col3"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div><div class="col4"><music-link role="link" kind="secondary" class="hydrated"><!----><span></span><div class="tags"></div></music-link></div></div></music-image-row></div></div></div></div></div></div></div>

**Comment by chimkle** [comment] 2020-10-31 20:26
![amazon1](https://user-images.githubusercontent.com/73549580/97789280-28931a80-1b8d-11eb-9c5a-2e8785c6f764.png)
When I play a song, it doesn't identify it right away, but when I scroll down my playlist (which is like 1000 songs) it recognizes the song.
![amazon2](https://user-images.githubusercontent.com/73549580/97789301-51b3ab00-1b8d-11eb-85b7-28019d49d1e4.png)
However, when I skip to the next song it doesn't recognize it even if I try scrolling.

**Comment by georgebounacos** [comment] 2020-12-02 20:29
This has been an issue for me using Amazon US too. I'm happy to help give any other info that's needed.

**Comment by inverse** [comment] 2020-12-02 20:32
Looks like the updated landed in DE - will try and fix it

**Comment by inverse** [comment] 2020-12-02 20:38
@georgebounacos What pages in particular are not working for you? I'm unable to reproduce :(

**Comment by georgebounacos** [comment] 2020-12-02 20:47
just today, I had this issue using the Alexa workaround.

open Alexa website to Now Playing Tab
https://alexa.amazon.com/spa/index.html#player

and then play music via voice commands on Echo.

Lately I've taken to opening three tabs:
Amazon Alexa link above
Last.fm profile
Amazon Music page in case I want to check something

The scrobble popup shows 75%+ of the time. If it doesn't show on the first
track, it will miss the whole session.

That happened earlier today. I stopped the Echo, closed the tabs, reopened
the tabs, restarted the music on Echo and it's scrobbling.

I'm using Windows 8.1 & Brave.

**Comment by inverse** [comment] 2020-12-02 20:48
@georgebounacos This sounds like another issue (regarding the Alexa SPA).

Could you open another issue which captures this please :)

**Comment by inverse** [comment] 2020-12-02 20:49
@rahonejm is this still an issue for you? I'm unable to reproduce :(

**Comment by rahonejm** [comment] 2020-12-03 05:38
I've just tested on @inverse's request it and I'm happy to report the problem seems to be gone. The addon now detects every track from stations, not just the first one. I can't say for how long the addon has been working properly since I had deactivated it ever since this thing started. I guess all that's left is confirmation from other people who had this problem that it's now also working for them.

**Comment by chimkle** [comment] 2020-12-07 18:37
Im still having issues with the scrobbler not detecting, even after reinstalling and trying on 2 different browsers.

**Comment by sunasaji** [comment] 2020-12-18 17:56
I also having issue with the scrobbler not detecting, and fixed it for my environment.
I want to know if it fixes the issue, and do no harm to the other users.
So could you help testing the sample version and report the result?

-Do you have scrobbling issue? (Yes/No)
-Do you have scrobbling issue with this sample version 2.39.0.1? (Yes/No)
-Which amazon music site are you using? ()
-Which browser/version are you using? ()
-Are you using new player or old player? (New/Old)
 You can check it by pressing F12 key on the amazon music site, and open console tab, then you can see:
 "Web Scrobbler: Setup connector for the new player" or
 "Web Scrobbler: Setup connector for the old player".

For example, my case is:
-Do you have scrobbling issue? (Yes)
-Do you have scrobbling issue with this sample version 2.39.0.1? (No)
-Which amazon music site are you using? (amazon.co.jp)
-Which browser/version are you using? (Google Chrome, 87.0.4280.88)
-Are you using new player or old player? (New)

[firefox-web-scrobbler-amazon-fix.zip](https://github.com/web-scrobbler/web-scrobbler/files/5717259/firefox-web-scrobbler-amazon-fix.zip)
[chrome-web-scrobbler-amazon-fix.zip](https://github.com/web-scrobbler/web-scrobbler/files/5717260/chrome-web-scrobbler-amazon-fix.zip)

**Comment by jupiterssj4** [comment] 2021-01-21 14:32
I found this site because:
1. Amazon Music won't scrobble anything other than albums or single songs (no radio stations or playlists) and 
2. The most major item, it won't scrobble if the window isn't open and up on the screen. If Amazon Music isn't the active tab in a number of tabs it won't scrobble. Therefore, I have to open another browser window and have it running on another monitor now. If you have it on another, non-visible tab, as soon as you switch back to the tab that Amazon Music is open on, you can see the scrobbler icon go from grey to green and it scrobbles.
3. It won't scrobble the album, only the track and artist (it says null in the console in F12).

I've always used Google Play Music until it stopped and then I switched to Amazon music HD. Google Play Music would scrobble no matter what, if it was the active tab, or a pinned tab, or not the active tab, or minimized, etc. 

-Do you have scrobbling issue? (Yes/No) **YES**
-Do you have scrobbling issue with this sample version 2.39.0.1? (Yes/No) **??**
-Which amazon music site are you using? () **music.amazon.com (USA)**
-Which browser/version are you using? ()  Chrome 88.0.4324.96 (Official Build) (64-bit)
-Are you using new player or old player? (New/Old) **NEW**
You can check it by pressing F12 key on the amazon music site, and open console tab, then you can see:
"Web Scrobbler: Setup connector for the new player" or
"Web Scrobbler: Setup connector for the old player".

Thank you, hope you can fix it.

**Comment by DisshanM** [comment] 2021-08-04 11:28
I am also having issues with scrobbling playlists on Amazon Music
-Do you have a scrobbling issue? (Yes/No) YES
-Do you have a scrobbling issue with this sample version 2.39.0.1? (Yes/No). **I use v2.45.0**
-Which amazon music site are you using? **music.amazon.in (India)**
-Which browser/version are you using? **Chrome v92.0.4515.107 (Official Build) (x86_64)**
-Are you using a new player or an old player? (New/Old) **NEW**

Hope you can fix it :)

**Comment by sunasaji** [comment] 2021-08-10 13:27
I updated the patched version for 2.45.0.

My case:
-Do you have scrobbling issue? (Yes)
-Do you have scrobbling issue with this sample version 2.45.0.1? (No)
-Which amazon music site are you using? (amazon.co.jp)
-Which browser/version are you using? (Google Chrome, 92.0.4515.131 (Official Build) (64-bit))
-Are you using new player or old player? (New)

[chrome-web-scrobbler-amazon-fix-2.45.0.1.zip](https://github.com/web-scrobbler/web-scrobbler/files/6961952/chrome-web-scrobbler-amazon-fix-2.45.0.1.zip)
[firefox-web-scrobbler-amazon-fix-2.45.0.1.zip](https://github.com/web-scrobbler/web-scrobbler/files/6961954/firefox-web-scrobbler-amazon-fix-2.45.0.1.zip)

How to load the sample version:
Chrome: https://developer.chrome.com/docs/extensions/mv2/getstarted/#manifest
- Download zip file and unpack it.
- Open Chrome "Extension" menu at the top-right and select "Manage Extensions" at the bottom.
- Enable "Developer mode" switch at the top-right.
- Find official "Web Scrobbler" and disable it.
- Click "Load unpacked" button at the top-left and select unpacked folder.
- Open Chrome "Extension" menu and find "Web scrobbler" and click pin icon at the right side.

Firefox: https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

**Comment by CharlesMatthews** [comment] 2021-08-16 21:12
Hey @sunasaji - thanks for this! 

Giving it a try now, but will let you know later this week on how it's working for me. 

My case: 

Scrobbling had been working fine for me when using Stations - but it would frequently break on individual tracks or albums.
I'd also find the extension not scrobbling unless the tab was a separate window (& even then had to be focused occasionally to scrobble).
It would also break when going to autoplay after a track had finished. 

Hoping this does the trick :) 

My case:
-Do you have scrobbling issue (v2.39.0.1)? (Yes)
-Do you have scrobbling issue with this sample version 2.45.0.1? (Testing now)
-Which amazon music site are you using? (amazon.co.uk)
-Which browser/version are you using? (Google Chrome, 92.0.4515.131 (Official Build) (64-bit))
-Are you using new player or old player? (New)

**Comment by sunasaji** [comment] 2021-08-29 16:33
Hi @CharlesMatthews 
Thank you for your report! The changed line is here:
```
src/connectors/amazon.js 
-	Connector.playButtonSelector = 'music-button[icon-name=play]';
+	Connector.pauseButtonSelector = 'music-button[icon-name=pause]';
```
https://github.com/sunasaji/web-scrobbler/commit/c324303f26a47763a7c95e0dcb047eb43bb684bc

**Comment by jo3rn** [comment] 2022-05-12 14:12
Scrobbling with playlists and stations works for me now with the new release. Give it a try.

**Comment by jupiterssj4** [comment] 2022-05-16 13:48
Thank you, I had been using a forum posted version for a long time that was a few versions older and I finally got rid of that and downloaded the new version from the chrome store and it seems to work well. Thank you!
    On Thursday, May 12, 2022, 10:12:30 AM EDT, Jörn Auerbach ***@***.***> wrote:  
 
 


Scrobbling with playlists and stations works for me now with the new release. Give it a try.

**Comment by jupiterssj4** [comment] 2022-05-16 19:38
STILL BROKE: My comment before was premature. The same issue that made me switch to the modified testing one posted here is still active. If the Amazon Music tab is not the visible tab, then it does not scrobble. Amazon made a change in last few days where sometimes scrobbling a new album won't start the scrobbling but an F5 fixes that (seems unrelated and both the new version and the test version are both affected). However, the major bug for me is still present. It won't scrobble when Amazon Music isn't the active tab and I always have it in a pinned tab next to what I'm actually working on.

**Comment by inverse** [comment] 2022-05-16 19:43
Sounds like the MutationObserver isn't setup properly if it doesn't register album changes :/

**Comment by inverse** [comment] 2023-06-16 19:44
@jupiterssj4 Is this still an issue with the new version? I can't reproduce it now.

**Comment by jo3rn** [comment] 2023-06-16 19:57
> @jupiterssj4 Is this still an issue with the new version? I can't reproduce it now.

for me it works

**Closed** 2023-06-16 20:12 UTC
Labels: bug, confirmed, connector, help wanted
