### ISSUE TITLE
Not working with Soundcloud

### ISSUE THREAD

**Issue by githubsucks-usegitlab** [web-scrobbler/web-scrobbler#2098] opened 2019-10-15 17:59 UTC
**Describe the bug**
Soundcloud doesn't work any more. Stopped working on Monday. Cleared cache, cookies, you name it. Logged out and in. Tried new windows, incognito. Blah blah. It won't detect that a song is playing. Also tried a dozen different songs in case it had to do with an ID issue.

**How to reproduce**
1. Go to Soundcloud.com
2. Click on Any song
3. Song isn't detected, and isn't scrobbled.

**Expected behavior**
The extension should be able to detect the playing music. I've tried to refresh the page, open a new window. Close chrome completely etc. it used to work with Soundcloud but now it doesn't.

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: Latest

**Comment by alexesprit** [comment] 2019-10-15 18:01
1. This is a duplicate of #2090.
2. This is already fixed and patch update is published (but not reviewed in Chrome Web Store yet).

**Closed by alexesprit** 2019-10-15 18:01 UTC
Labels: bug
