### ISSUE TITLE
Scrobbler not working on Safari

### ISSUE THREAD

**Issue by sontopo** [web-scrobbler/web-scrobbler#4428] opened 2024-01-15 13:47 UTC
The scrobbler is enabled on Safari, I signed in Last.fm, after updating the options it appears again as not signed in, so it’s not scrobbling anything.

**Comment by yayuyokitano** [comment] 2024-01-15 13:57
Unable to reproduce on macos 13.4 / safari 16.5. Could you try running the following? `await browser.storage.local.get("LastFM")` (cmd+option+i then click "console" on the top of the dev tools that appear)
Make sure to censor whatever is in `sessionID` if there is anything.
Could you also try to send a screen recording of you clicking sign in, signing in, and checking back in on options?

**Comment by sontopo** [comment] 2024-01-15 14:47
Okay, mb, I didn't mention I was doing it on iOS. I guess there's no way to do it for iOS?

> Unable to reproduce on macos 13.4 / safari 16.5. Could you try running the following? `await browser.storage.local.get("LastFM")` (cmd+option+i then click "console" on the top of the dev tools that appear) Make sure to censor whatever is in `sessionID` if there is anything. Could you also try to send a screen recording of you clicking sign in, signing in, and checking back in on options?

**Comment by yayuyokitano** [comment] 2024-01-15 14:58
There is, but it’s not so simple. That said I cannot reproduce on iOS either.

one caveat is that login is not finalized until you actually return to the settings. In iOS this is a little clunkier than in PC browsers so I could see a world where the user doesn’t. Issue is that lastfm has a timeout on login, so if it goes a few minutes without returning to options the sign in will not be finalized. Could this be the issue?

**Comment by sontopo** [comment] 2024-01-15 15:04
Tried again few times without updating options of scrobbler and now appears like this and scrobbling 😄 Any way to use it while locked? I thought that with premium I could!![image](https://github.com/web-scrobbler/web-scrobbler/assets/104890279/2eabd0ed-3b91-4da0-8e03-50b221590977)

**Comment by yayuyokitano** [comment] 2024-01-15 15:35
Unfortunately youtube mobile in browser is quite buggy (probably intentionally so). However playing a single video while locked is perfectly doable even without premium (premium only affects app). Playlists you may see worse results.

some things you can try to improve reliability:
- Make sure to lock screen while video is already playing. You may get the media center thing on your lock screen where you can resume the video. It will scrobble.
- try locking while in full screen.
- Try locking while in picture-in-picture (youtube automatically kills PIP, but if you lock immediately after you click tap the button it will lock before animation finishes and youtube kills it.

**Comment by yayuyokitano** [comment] 2024-01-16 21:10
Closing since core issue is solved. That said feel free to continue asking questions if there is anything, I am still following this thread.

**Closed by yayuyokitano** 2024-01-16 21:10 UTC
Labels: bug
