### ISSUE TITLE
tracks began to be added to favorites on their own

### ISSUE THREAD

**Issue by agatkasomnia** [web-scrobbler/web-scrobbler#4589] opened 2024-03-16 07:47 UTC
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by inverse** [comment] 2024-03-16 08:41
I'm unable to reproduce this. Can you provide more context based on the template provided when creating issues.

**Comment by inverse** [comment] 2024-03-16 08:54
Will be fixed in the next release

**Closed by inverse** 2024-03-16 08:54 UTC
Labels: bug
