### ISSUE TITLE
Please make permissions more granular

### ISSUE THREAD

**Issue by lukehunter** [web-scrobbler/web-scrobbler#440] opened 2014-08-20 18:22 UTC
Why does this extension need chrome permissions for all sites? Could it be limited to the sites that the scrobbler is actually reading from?

**Comment by carlin-q-scott** [comment] 2019-01-17 18:38
I've implemented this for my media player control extension, but only for user configurable sites; it already requests permissions for most multimedia websites.

To implement this yourself, you need this [optional permission in your manifest](https://github.com/carlin-q-scott/browser-media-players/blob/master/manifest.json#L61-L63) and then [here's some example code of how to request the permission](https://github.com/carlin-q-scott/browser-media-players/blob/master/options/ContentScriptOptions.js#L51-L55).

You can test out this functionality by installing my extension from [here](https://github.com/carlin-q-scott/browser-media-players/releases), opening the options page and setting one of the custom domains at the bottom to a common website, such as `https://msn.com/*`. The permission is requested the moment you open the targetted website.

You may be able to talk me into implementing this for you in a PR, but I suspect implementing it would require way more knowledge of your code than my code.

**Comment by marsjaninzmarsa** [comment] 2019-01-31 08:56
> I've implemented this for my media player control extension, but only for user configurable sites; it already requests permissions for most multimedia websites.
> (....) setting one of the custom domains at the bottom to a common website, such as https://msn.com/*. The permission is requested the moment you open the targetted website.

O'rly? 😅
![obraz](https://user-images.githubusercontent.com/1119575/52042652-fed33c80-253d-11e9-97d9-6d79ae03d034.png)
Translation: this addon requests following permissions: access to data on all websites.

**Comment by inverse** [comment] 2019-06-12 18:28
Is this even feasible?

**Comment by alexesprit** [comment] 2019-06-12 18:37
This issue can be resolved with at least two ways:
1. Use browser.permissions API to ask user to allow accessing the website content.
2. Merge data from `connectors.js` into manifest file when building the extension.

The first one is really awful, as users should click on "Yes" every time page is reloaded. The second way is better, but as David said previously, it has a drawback:
> I switched to "all sites" permission a long time ago. It was because of the extensions security which requires user to re-allow the extension every time its permissions change. That means every update with support for a new site basically disabled the extension.

I don't like both ways and prefer to keep things as-is.

**Comment by inverse** [comment] 2019-06-12 18:47
for 1 is that a one time thing or on each load? That would suck.

For 2 - that would require a build step to run unpacked. If we're going down that route there is a lot we could do to improve.

If there is nothing reasonable right now should we close this?

**Comment by alexesprit** [comment] 2019-06-12 18:55
> for 1 is that a one time thing or on each load? That would suck.

Don't remember exacly, on each load or tab session. Anyway, it's really not user friendly.

> For 2 - that would require a build step to run unpacked. If we're going down that route there is a lot we could do to improve.

No, it won't require any steps. Everything will be the same for those who run the extension as unpacked. I'm talking about adding data from `connector.js` to manifest and removing injecting code while compiling the extension. The release version will use browser mechanism to inject scripts.

I think current implementation is preferrable for most users, and the issue should be closed.

**Closed** 2019-06-12 19:16 UTC
Labels: blocked, discussion

**Comment by carlin-q-scott** [comment] 2019-06-12 23:23
@marsjaninzmarsa 
> Translation: this addon requests following permissions: access to data on all websites.
Strangely enough, that isn't caused by the optional_permission for all domains. I fixed it by [removing permissions for the file:// protocol](https://github.com/carlin-q-scott/browser-media-players/commit/a33bb79694d158269d033dbb594964ce64efed6a).

**Comment by carlin-q-scott** [comment] 2019-06-13 00:16
@alexesprit are you sure that the permissions disapear on page reload? Allowed permissions persist through extension updates so I think they're pretty persistent. If someone denies the permission then the permissions API may not keep a record and re-ask on page reload. You could deal with that by saving denied requests using the storage api. Or just let people deal with getting asked a bunch when they deny a permission since right now you're not even giving them a choice.

**Comment by alexesprit** [comment] 2019-06-13 05:19
> @alexesprit are you sure that the permissions disapear on page reload?

Here's my implementation: https://github.com/web-scrobbler/web-scrobbler/tree/feature/optional-permissions. Yes, after I do page reload, the browser asks me to allow to disallow access to the website.

I'm on Opera, btw.

**Comment by carlin-q-scott** [comment] 2019-06-13 21:03
For Chrome and Firefox, we cannot request permissions outside of a user gesture. I'm capturing the exception in my branch off of yours: https://github.com/carlin-q-scott/web-scrobbler/tree/feature/optional-permissions

![chrome_2019-06-13_13-54-03](https://user-images.githubusercontent.com/2521644/59466979-6dc17b80-8de3-11e9-92f1-45053c9fa8f6.png)

Perhaps Opera is allowing the permission request but not acting on it?

I didn't run into user gesture requirement with my extension because I'm requesting permission after a user saves settings. However I did attempt to implement this feature for your extension a while back and ran into this same issue and gave up. The solution I came up with was to have the user click on the extension icon to enable the website but I didn't get far enough in implementing that before I lost interest.
