### ISSUE TITLE
Bug: Won't scrobble tracks from Plex anymore

### ISSUE THREAD

**Issue by bendotf** [web-scrobbler/web-scrobbler#2774] opened 2021-03-18 23:16 UTC
For the past couple days, the Web Scrobbler on Chrome isn't scrobbling songs from Plex anymore. Just says "Play some music to get started" when the tracks are playing. Maybe the connector code needs to be updated.

**Comment by alexesprit** [comment] 2021-03-19 05:41
Closed as a duplicate of #2764.

**Closed by alexesprit** 2021-03-19 05:41 UTC
Labels: bug
