### ISSUE TITLE
Chrome crashing/Chrome Unresponsive

### ISSUE THREAD

**Issue by noablimi** [web-scrobbler/web-scrobbler#3830] opened 2023-06-01 01:27 UTC
My Google Chrome is crashing after playing any song from this Beatles album: https://music.youtube.com/playlist?list=OLAK5uy_kx7E82d6vaFm76vkXtcvzr89qsh8zaqEs - it scrobbles after some time but my Chrome page is frozen and with no sound
On this one, the scrobbling works, but the Web Scrobbler acts weird: https://music.youtube.com/playlist?list=OLAK5uy_n0G_dg7mTxrWUFfRy2fFxQ3Y-8Jav9MH0 - the scrobbler don't let me see scrobble tags/stats. But regex works normally.

**How to reproduce**
1. Go to those links (https://music.youtube.com/playlist?list=OLAK5uy_kx7E82d6vaFm76vkXtcvzr89qsh8zaqEs) for "chrome is not responding", "https://music.youtube.com/playlist?list=OLAK5uy_n0G_dg7mTxrWUFfRy2fFxQ3Y-8Jav9MH0" for web scrobbler acting weird
2. Click on any song from any of those albums
3. See error

**Expected behavior**
The track i clicked plays and the extension scrobbles normally.

**Screenshots**
![Screenshot 2023-05-31 185140](https://github.com/web-scrobbler/web-scrobbler/assets/43256327/49cdcf47-46e9-41bf-bc15-6fdc8aedca83)
![Screenshot 2023-05-31 195500](https://github.com/web-scrobbler/web-scrobbler/assets/43256327/0c29d4d1-0e5a-4d79-8cac-9917b6c4c9f9) < ----- after playing any song from the Then Play On [Expanded Edition] album, that is how the extension is displayed.

**Debug logs**
https://pastebin.com/dS1KuRXQ - Logs of the Background Script
https://pastebin.com/yWBzqeBJ - Logs of Content Scripts

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Chrome
-   Extension version: 3.0.10

**Additional context**
I have a bunch of regexes. It is probably what is causing this issue. After removing the Web Scrobbler extension and adding it again, with no regexes and with my edits only, I tried to listen to a song from both albums and it scrobbled normally. I don't know how to paste them directly on GitHub, so i added them here: https://drive.google.com/drive/folders/1e5QNfHoidAnEsC5Z961BASxQot5Bl-9z?usp=sharing

**Comment by yayuyokitano** [comment] 2023-06-01 01:43
This seems to be single-handedly caused by the regex that searches for `([^(]+)*\s\([^)]*[Ll]egacy[^)]*\)|([^\[]+\s*)\[[^\]]*[Ll]egacy[^\]]*\]` and replaces it with `$1`. What is the goal of this regex?

**Comment by noablimi** [comment] 2023-06-01 02:09
> This seems to be single-handedly caused by the regex that searches for `([^(]+)*\s\([^)]*[Ll]egacy[^)]*\)|([^\[]+\s*)\[[^\]]*[Ll]egacy[^\]]*\]` and replaces it with `$1`. What is the goal of this regex?

It is for removing Legacy album tags that are in parenthesis (Legacy Edition) for example, like these ones: https://music.youtube.com/playlist?list=OLAK5uy_lIHPUjsWzolSeRY2oJzuHdkzeAc4WvuLg
https://music.youtube.com/playlist?list=OLAK5uy_lQf9Uo3BZliA5EJOh3xnV0CDTdnRgEO_o
But Web Scrobbler is working fine with these albums

**Comment by yayuyokitano** [comment] 2023-06-01 02:24
Aight, then I think having two separate regexes `(.+?)\s+\([^(]*[Ll]egacy.*?\)` and `(.+?)\s+\[[^[]*[Ll]egacy.*?\]` both with $1 as replace might be more sane.

There's some sort of loop in your original regex, not sure exactly where due to how complex it is.

For the future, we should implement the regex function into a web worker, which should allow buggy regex to fail gracefully and allow us to provide debugging opportunities for the user.

**Comment by painchen88** [comment] 2023-06-01 08:46
Same with my google chrome browser. It crashes or the page hangs. Since the last update, too much RAM is required, so everything is too memory-intensive.

**Comment by yayuyokitano** [comment] 2023-06-01 09:18
> Same with my google chrome browser. It crashes or the page hangs. Since the last update, too much RAM is required, so everything is too memory-intensive.

This sounds like it is probably unrelated to original issue. Can I ask what version of web scrobbler you currently have installed?

If it is older than 3.0.9, please try updating the extension, as 3.0.9 had some big performance patches.

While it seems unlikely, if you got the extension from the edge marketplace, they recently approved the wrong version and it is now outdated, we are trying to resolve this.

**Comment by noablimi** [comment] 2023-06-01 13:33
> Aight, then I think having two separate regexes `(.+?)\s+\([^(]*[Ll]egacy.*?\)` and `(.+?)\s+\[[^[]*[Ll]egacy.*?\]` both with $1 as replace might be more sane.
> 
> There's some sort of loop in your original regex, not sure exactly where due to how complex it is.
> 
> For the future, we should implement the regex function into a web worker, which should allow buggy regex to fail gracefully and allow us to provide debugging opportunities for the user.

yeah, it seems like it was that regex. i removed it and now it's working fine!! i replaced it for this one: `^(.*?)\s+[\(\-\[].*?[Ll]egacy.*` and now everything is working good. btw thank you very much for this feature, it saves me a lot of time :))

**Comment by yayuyokitano** [comment] 2023-06-02 00:20
Closing since original issue is solved. @painchen88 if you are still experiencing your issue on 3.0.9/3.0.10, please open a new issue.

**Closed by yayuyokitano** 2023-06-02 00:20 UTC
Labels: bug
