### ISSUE TITLE
Album (or album cover) is detected incorrectly (or not detected) on Music.Yandex sometimes

### ISSUE THREAD

**Issue by RAM237** [web-scrobbler/web-scrobbler#2001] opened 2019-06-24 15:50 UTC
**Describe the bug**
Music.Yandex: from time to time album is detected incorrectly (or not detected at all).
Also sometimes the album cover displayed is not from the album currently playing (this is way less important, btw).

**How to reproduce**
1. Go to "https://music.yandex.ru/album/4852" (ABBA's album "Voulez-Vous")
2. Click on Play, e.g. for "I Have A Dream" track
3. Click on extension icon in the top right and check the data

**Expected behavior**
1. OK
2. OK, track is playing
3. For some reason it detects "Gold: Greatest Hits" as an album (not only for this track, but for some other tracks too, however, sometimes it shows the album correctly). From time to time the album is not detected at all (empty), but I am playing tracks from the specific album page, shouldn't be an issue to detect it (no such issue seen for Bandcamp, for example).
Also, even if the album is detected correctly, it shows the album cover of different album sometimes.

**Environment (please complete the following information)**
-   OS: Windows 10 Enterprise
-   Browser: Chrome 75
-   Extension version: 2.20.2

**Comment by alexesprit** [comment] 2019-06-24 16:49
Unfortunately, I'll probably mark this issue as "won't fix" and close, as, it's not a bug, but a lack of album info on the player bar and some limitations.

> I am playing tracks from the specific album page, shouldn't be an issue to detect it (no such issue seen for Bandcamp, for example).

The current architecture requires track info being displayed all the time. It won't be changed in near future. Bandcamp displays album info all the time, and does not use AJAX navigation.

As a fallback, the extension requires album title from Last.fm, but it returns wrong album info sometimes.

> Also, even if the album is detected correctly, it shows the album cover of different album sometimes.

The extension does not use cover arts from Yandex. They provide small (50x50) cover arts, and I think it's better to use the ones from CoverArtArchive or Last.fm.

**Closed** 2019-06-25 10:41 UTC
Labels: won't fix

**Comment by alexesprit** [comment] 2019-10-05 20:21
@RAM237 the connector is now powered by Yandex API, so both album and album cover is displayed correctly. This change will be available in the next release.
![image](https://user-images.githubusercontent.com/1119267/66260395-c4095e80-e7c6-11e9-8a19-c601ea85dd76.png)

**Comment by RAM237** [comment] 2019-10-06 19:40
Hi! This is amazing! Thanks for letting me know and HUGE thanks for implementing this!
I also have a few ideas for improvements, and likely I will file them here soon, when I have time.
Cheerz!
