### ISSUE TITLE
Youtube scrobbling isn't working

### ISSUE THREAD

**Issue by dimatz** [web-scrobbler/web-scrobbler#1897] opened 2019-02-03 00:18 UTC
When I watch music videos on youtube and after the title is recognized by the extension, it says that some kind of error occurred and I should re-login. But re-login can't solve this problem. Cleared all cache and cookies, reinstalled the extension. Nothing helps.

**Comment by SirPhteven** [comment] 2019-02-04 11:16
same here

**Comment by danielmlipton** [comment] 2019-02-04 23:53
Just started happening here, too.  Did either of you see any changes in behavior since you reported the issue or find a solution?

**Comment by dimatz** [comment] 2019-02-05 01:00
> 15 minutes after posing it began working on its own.

Glad for you. On my setup it ist't working for couple months.

**Comment by ExpandingShapes** [comment] 2019-02-05 01:44
Well, I don't scrobble from YT much, but I'm listening to music on YT right now. And everything works fine.
@dimatz Have you tried reinstalling the unpacked version of the extension?

**Comment by dimatz** [comment] 2019-02-05 08:38
> @dimatz Have you tried reinstalling the unpacked version of the extension?
No. Can't find it now actually.

**Comment by inverse** [comment] 2019-02-11 20:52
Got sample URL?

**Comment by 3xploiton3** [comment] 2019-03-01 00:31
did'nt work for any youtube

https://www.youtube.com/watch?v=09R8_2nJtjg

![image](https://user-images.githubusercontent.com/19517680/53608069-e1a09500-3bf3-11e9-823b-787e6649de00.png)

**Comment by inverse** [comment] 2019-03-02 20:07
It's the rate limiting of the YT API since we rely on this for matching the music category.

**Comment by JediJoker** [comment] 2019-03-06 01:11
So the issue is with YouTube's API? Nothing to be done?

**Comment by alexesprit** [comment] 2019-03-06 09:09
We have a solution in #1919, and we were testing and improving that approach yesterday. It works fine now, and it should be merged soon. Plus, I did some trick with current YT API key, and, probably, it can resolve the issue.

**Comment by inverse** [comment] 2019-03-06 19:17
Leading on what what @alexesprit mentioned. The release was published so you should be able to use YT again.

**Closed by inverse** 2019-03-06 19:17 UTC
Labels: bug, connector
