### ISSUE TITLE
Spotify Connector broken again

### ISSUE THREAD

**Issue by MXB2001** [web-scrobbler/web-scrobbler#3581] opened 2023-02-19 01:43 UTC
**Describe the bug**

Spot's stopped scrobblin'...

**How to reproduce**
1. Go to Spotify
2. Click on Music Box Dancer by Frank Mills

**Expected behavior**
Scrobbling (aka the Red icon turning green)

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
Linux
-   Browser: (e.g. Chrome, Safari)
Firefox
-   Extension version: (e.g. v2.10.0)
latest update as of 10 seconds ago
- did not work before update or after

**Comment by MXB2001** [comment] 2023-02-19 04:54
Update! It scrobbles but like I wrote the icon does not change when it does. It stays red and says nothing being scrobbled while on the other hand last fm actually shows them being scrobbled.

**Comment by yayuyokitano** [comment] 2023-02-19 05:12
Duplicate of #3575 

The new version 2.86.1 with fix has already been pushed, and is pending approval from Mozilla.

There is unfortunately nothing we can do except wait for Mozilla to approve.

**Closed by yayuyokitano** 2023-02-19 05:12 UTC
Labels: bug
