### ISSUE TITLE
YouTube Music won't scrobble Music

### ISSUE THREAD

**Issue by Bourscheid** [web-scrobbler/web-scrobbler#1788] opened 2018-11-05 13:41 UTC
### Expected behavior
The music is playing but scrobbler isn't recognizing.

### Current behavior
Before last release Scrobbler was showing this message: "This website is not supported -
Web Scrobbler does not support scrobbling from this website." and now, Scrobbler shows the follow messege: "Play some music to get started - Is it already playing?".

### Context
Yesterday it was scrobbling normally, but today it's not working anymore. In fact I was using another computer. But it suppous to work on every Chrome browser, right?

### Environment
* Version used: Web Scrobbler version 2.7.0
* Browser name and version: Google Chrome - Version 70.0.3538.77 (official) 64 bits

**Comment by inverse** [comment] 2018-11-05 20:06
Do you have a sample URL?

**Comment by Bourscheid** [comment] 2018-11-06 18:07
I'm sorry. For me every URL from music.youtube.com domain is not scrobbling.

**Comment by AtomSh** [comment] 2018-11-06 21:23
I have the same problem.

**Comment by restinginlove** [comment] 2018-11-07 18:44
Weirdly mine started working with the latest release, but it's double scrobbling. I only have youtube music checked in the options (I don't want anything from the main youtube.com to scrobble, just music.youtube.com), so I'm not sure how it's double scrobbling.

**Comment by akaAndyDaSilva** [comment] 2018-11-07 22:39
Me too [Youtube Music](https://music.youtube.com/) ... I hope this could work soon 👍

**Comment by inverse** [comment] 2018-11-08 07:00
It's been deployed 2 releases ago. It's working for me. Could you provide a sample URL that doesn't work?

**Comment by Bourscheid** [comment] 2018-11-08 13:44
For me, none of URL are scrobbling.
For example, this one: https://music.youtube.com/watch?v=A_N2ufOJ5bg&list=OLAK5uy_kvKHq64wUp2eq0EJaPv_3379O1I26fVO4

**Comment by inverse** [comment] 2018-11-08 13:48
@Bourscheid this is working for me :(

![image](https://user-images.githubusercontent.com/713525/48202492-590c9900-e365-11e8-9eec-616db8d745d4.png)

**Comment by restinginlove** [comment] 2018-11-08 17:48
> Weirdly mine started working with the latest release, but it's double scrobbling. I only have youtube music checked in the options (I don't want anything from the main youtube.com to scrobble, just music.youtube.com), so I'm not sure how it's double scrobbling.

I'm dumb and forgot I had installed a YTmini for youtube extension too and was logged into last.fm on there too. Hence the dual scrobbles. Nevermind, but for those who are having issues scrobbling right now, try that extension in the meantime?

**Comment by Bourscheid** [comment] 2018-11-08 20:04
@inverse I tryed to reinstall scrobbler, but still not working.
![capturar](https://user-images.githubusercontent.com/6320856/48224405-c548c600-e380-11e8-9611-843007d3b246.JPG)

**Comment by reitzig** [comment] 2018-11-09 08:50
Works here as well.

![image](https://user-images.githubusercontent.com/4246780/48252368-e3f0a080-e404-11e8-8d92-acc1748c7fd9.png)

**Comment by akaAndyDaSilva** [comment] 2018-11-10 10:12
I think that the issue is related to the localization

I change mine from Brazil to the United States, and now it's work well even if I return to localization Brazil

![image](https://user-images.githubusercontent.com/1809812/48300199-67bb9300-e4c0-11e8-92bb-28a6b43515e3.png)

**Comment by martdiv** [comment] 2018-11-10 13:59
I think it's related to language, not location. 
I changed mine from BRA to USA and still didn't work. When I changed the language to English, it began scrobbling correctly.

**Comment by inverse** [comment] 2018-11-10 20:09
Flagging this as an active bug :+1:

**Comment by Whateverthing** [comment] 2018-11-11 18:56
I confirm, same problem for me, all YouTube music is no longer recognized by the scrobbler. I just tried un-installing and re-installing the extension, but no change.

**Comment by Bourscheid** [comment] 2018-11-12 12:40
Thank you all guys. You're amazing.

**Comment by inverse** [comment] 2018-11-12 21:40
@jaccarmac any ideas? It's something to do with the locale?

**Comment by jaccarmac** [comment] 2018-11-12 21:44
I only use EN (in fact I'm the stereotypical clueless English speaker who doesn't even know how to change it) but I'm seeing the same issue. Maybe something changed on the site. Google's known to AB test so that would explain the fact that some people can still scrobble.

**Comment by inverse** [comment] 2018-11-12 21:46
I changed my locale from en-GB to de-DE and saw the samething as expressed above. Couldn't see anything obvious either :/

**Comment by jaccarmac** [comment] 2018-11-12 21:53
Aaand it's working for me again a couple minutes later. If anyone can duplicate the issue reliably they could take a look at the selectors. I would be especially suspicious of the one linked below as it contains very English-specific text.

https://github.com/web-scrobbler/web-scrobbler/blob/ea7f3ada83e267b304408773a75dd75ee6839f4a/src/connectors/youtube-music.js#L19

**Comment by James-W2** [comment] 2018-11-13 11:08
Web Scrobbler version 2.6.0 has been working sporadically for me for awhile.  I have noted that it would not scrobble tracks from playlists or Mixes, but would scrobble individual tracks/videos.  It was doing this through Monday afternoon.  However, this evening it quit scrobbling YouTube altogether.  I upgraded Google Chrome to Version 70.0.3538.102 (Official Build) (64-bit) and updated the Scrobbler to **version 2.8.1.**  Now it is scrobbling music videos okay.  I haven't tried to scrobble from a playlist or mix yet, however.  Hope updating the Scrobbler will help others as well.

**Comment by Bourscheid** [comment] 2018-11-13 15:57
Since I started to use Youtube Music I noticed that Youtube (videos) now have some artists profiles called Topics, and if you're listening to mixes from a YouTube topic, it doesn't scrobble. I think it happen because music names follow another pattern. But today YouTube Scrobble stopped to work at all.

**Comment by xuanruiqi** [comment] 2018-11-13 22:34
YouTube scrobble stopped working yesterday.

**Comment by Potencial** [comment] 2018-11-21 13:35
its something with the language, changing language to English (US) it works

**Comment by njack21** [comment] 2018-11-21 18:21
Following

**Comment by njack21** [comment] 2018-11-21 19:12
> its something with the language, changing language to English (US) it works

My language is English (US) and scrobbling not working.

**Comment by hangy** [comment] 2018-11-23 15:43
Could it be an issue in this line?
https://github.com/web-scrobbler/web-scrobbler/blob/2fbfd1cd012d65a9660893703f555ad686e0e205/src/connectors/youtube-music.js#L19
In the German locale, it's "Pausieren" instead of "Pause" (and "Wiedergabe" while playing). Because of that, the scrobbler might never see the track as playing.

**Comment by jaccarmac** [comment] 2018-11-23 16:09
Yeah, that's just it. Problem is that I couldn't figure out a better way than title to get the state of that button. I'll do some digging.

**Comment by akaAndyDaSilva** [comment] 2018-11-26 00:09
It's too hard to use the SVG to identify the state of that button

I think it's not ideal, but seems to work well in any language

![image](https://user-images.githubusercontent.com/1809812/48986608-8d6eac00-f0fe-11e8-81ea-6e293b68c25b.png)

**Comment by xuanruiqi** [comment] 2018-11-27 00:07
It's fixed for me, don't know about everyone else...

**Comment by James-W2** [comment] 2018-11-27 03:31
I'm currently using Version 2.9.0 and latest version of Chrome, with YouTube scrobbling OK (so far).

**Comment by njack21** [comment] 2018-11-28 17:04
Scrobbling is now working for me.




<https://sites.google.com/a/google.com/gps-email-signature/home/Google_Signature4.png?attredirects=0>

*  •  **Neal Jack*

*  • * Dude TPM

*  •  *njack@google.com

  •  Google LLC


Once again, the given name is Neal and the surname is Jack.

**Comment by Ploppy33** [comment] 2018-11-29 16:43
I'm using Firefox 63.0.3 (on a Mac) and YouTube scrobbling stopped working for me since early last week.

**Comment by Ismaouste** [comment] 2018-12-03 10:11
My Youtube Music premium used to be in french, switched it to English US and it started scrobbling 👍(on chrome) !! Thanks a lot !

**Comment by Ploppy33** [comment] 2018-12-04 10:42
Unfortunately switiching to English US didn't work for me - I still can't scrobble my YouTube plays.

**Comment by njack21** [comment] 2018-12-05 17:36
And it's back to not working. No changes on my end.

**Comment by inverse** [comment] 2018-12-05 20:33
@jaccarmac & @akaAndyDaSilva  what do you think of my fix? basically checking the SVG path?

**Comment by jaccarmac** [comment] 2018-12-06 02:47
It was what I was planning on doing eventually but you beat me to it. @akaAndyDaSilva Thanks for the solution.

**Comment by xlipe** [comment] 2018-12-07 05:57
Mine is still not working. Is there any update coming with a fix?

**Comment by xlipe** [comment] 2018-12-07 06:09
> langua

thank you, it works now

**Comment by xlipe** [comment] 2018-12-07 06:09
> When I changed the language to English, it began scrobbling correctly.

thanks, it works

**Comment by James-W2** [comment] 2018-12-07 06:13
@inverse  Thanks so much for your work on a fix.  Any idea how long it takes for fixes to be included in an extension version update?

**Closed** 2018-12-07 18:21 UTC
Labels: bug, connector

**Comment by inverse** [comment] 2018-12-07 20:05
Can you confirm that the latest release solved he issue?  @James-W2 it's published.

**Comment by inverse** [comment] 2018-12-07 20:05
It should work independent of the locale now.

**Comment by James-W2** [comment] 2018-12-08 00:49
Yes, the latest release auto-installed in Chrome and I'm now able to scrobble YouTube, etc.  Thanks! 
James Whitley 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Malachi Soord <notifications@github.com> Date: 12/7/18  12:05 PM  (GMT-08:00) To: web-scrobbler/web-scrobbler <web-scrobbler@noreply.github.com> Cc: James-W2 <jtwhitley2@comcast.net>, Mention <mention@noreply.github.com> Subject: Re: [web-scrobbler/web-scrobbler] YouTube Music won't scrobble Music
  (#1788) 
Can you confirm that the latest release solved he issue?  @James-W2 it's published.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/web-scrobbler/web-scrobbler","title":"web-scrobbler/web-scrobbler","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/web-scrobbler/web-scrobbler"}},"updates":{"snippets":[{"icon":"PERSON","message":"@inverse in #1788: Can you confirm that the latest release solved he issue?  @James-W2 it's published."}],"action":{"name":"View Issue","url":"https://github.com/web-scrobbler/web-scrobbler/issues/1788#issuecomment-445349978"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/web-scrobbler/web-scrobbler/issues/1788#issuecomment-445349978",
"url": "https://github.com/web-scrobbler/web-scrobbler/issues/1788#issuecomment-445349978",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [web-scrobbler/web-scrobbler] YouTube Music won't scrobble Music (#1788)",
"sections": [
{
"text": "",
"activityTitle": "**Malachi Soord**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@inverse",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"web-scrobbler/web-scrobbler\",\n\"issueId\": 1788,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/web-scrobbler/web-scrobbler/issues/1788#issuecomment-445349978"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 406444895\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Defunktt1** [comment] 2018-12-19 10:09
Still not working for me
Firefox 64, Scrobbler v2.6.0
![2018-12-19 12 06 30](https://user-images.githubusercontent.com/22061913/50213565-acbbca80-0386-11e9-9ad4-ed0d7fd2f103.png)

**Comment by inverse** [comment] 2018-12-19 11:06
@Defunktt1 you'll need to update - `2.10.0` is the latest. Unfortunately the extension was removed from AMO due to analytics.

**Comment by Defunktt1** [comment] 2018-12-19 12:03
@inverse So sad :( Is any way to compile source code to .xpi file? I found guide how to add temporary extension only
