### ISSUE TITLE
Amazon Music Recently Added Tracks doesn't work with the Amazon tracker

### ISSUE THREAD

**Issue by patrickeplaza** [web-scrobbler/web-scrobbler#2616] opened 2020-10-28 20:37 UTC
**Describe the bug**
The new UI is kind of ugly and I hate using it. Playing tracks from recently added are not identified by the Amazon Music Connecter. The connector doesn't recognize tracks that I have recently added into my music. 

**How to reproduce**
1. Go to 'music.amazon.com'
2. Go to 'Library' then 'Music'
3. Then click on 'Songs'
4. Click 'Filter'
5. Change the filter to 'recently added'
6. Play the songs

If you try this, I expect you guys to have similar results, that the tracks there aren't being recognized.

**Screenshots**
![2020-10-28 13_14_24-Window](https://user-images.githubusercontent.com/73614484/97493627-7e17bf00-1922-11eb-85b4-f0ad98e5365d.png)

idk how to provide debug logs

**Environment (please complete the following information)**
-   OS: Windows
-   Browser: Brave and Chrome
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by alexesprit** [comment] 2020-10-28 21:28
Isn't it a duplicate of #2604?

**Closed** 2020-12-05 10:20 UTC
Labels: bug, outdated
