### ISSUE TITLE
Web scrobbler doesn't work on edge

### ISSUE THREAD

**Issue by Lulu-894** [web-scrobbler/web-scrobbler#4856] opened 2024-08-01 15:53 UTC
**Provide information about website**
A short description of the website, sample URLs, (demo) accounts for testing purposes. If (demo) accounts are not for public use, you can mail them to the project developers.

**Additional context**
Add any other context or screenshots about the request here.

**Comment by yayuyokitano** [comment] 2024-08-01 17:07
Duplicate of #4849 please see that issue for updates. The fix has already been pushed, just pending approval from edge store.

**Closed by yayuyokitano** 2024-08-01 17:07 UTC
Labels: connector, request
