### ISSUE TITLE
Amazon Music web player scrobbles wrong album

### ISSUE THREAD

**Issue by zachryzion** [web-scrobbler/web-scrobbler#1677] opened 2018-07-26 21:46 UTC
When scrobbling from https://music.amazon.com/stations, the album is scrobbled as the station name (in my case "Prime Alternative Station"), instead of the real album.
### Expected behavior

It should scrobble the real album for each song/Artist

### Current behavior

It scrobbles the station name

### Possible solution

Do not take the album from the station. I think by default you search for a possible album.

### Steps to reproduce (for bugs)

Log in to https://music.amazon.com/ and start any music station and you can see the scrobble activity.

1. Log on to https://music.amazon.com/stations
2. Fire up any station
3. See that it scrobbles the station name as the album.

### Context

3-4 days, ever since I have started the station.

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used: 67.0.3396.99
* Browser name and version: Chrome 67.0.3396.99

**Comment by clasick** [comment] 2019-12-12 18:19
After #2193, this bug is not reproducible. Since it won't take the station name as the album name, it gets scrobbled without an album name. Last.fm then tries to it using the Artist and Track name alone. 

I think this is the intended behavior at this point. Can close this.

**Comment by alexesprit** [comment] 2019-12-12 18:28
@clasick Thanks for the info.

**Closed by alexesprit** 2019-12-12 18:28 UTC
Labels: bug, confirmed, connector, help wanted
