### ISSUE TITLE
pls add the-radio and radiorecord

### ISSUE THREAD

**Issue by Greeple** [web-scrobbler/web-scrobbler#1989] opened 2019-05-25 13:01 UTC
Сan you add http://the-radio.ru and http://www.radiorecord.ru/ on the radio record site all track titles in the same place http://prntscr.com/nt6ofu and the the-radio site is just a good combine from different radios, better than all you have in connectors
Thanks!

**Comment by alexesprit** [comment] 2019-05-25 13:43
Closed as duplicate of #1869.

**Closed by alexesprit** 2019-05-25 13:43 UTC
Labels: connector, request

**Comment by Greeple** [comment] 2019-05-25 14:03
> Closed as duplicate of #1869.
> 
> Please, don't duplicate issues, it won't help to resolve them. :)

Why removed both issues? would leave this one if it was really so necessary, just you, for half a year, did not add them, and I did not see my message, and I thought that it had already been deleted, so I wrote again

**Comment by alexesprit** [comment] 2019-05-25 14:04
#1869 is not closed. If you open that issue, you can see it still is open and ready for someone who will resolve it.

**Comment by Greeple** [comment] 2019-05-25 14:05
ok
