### ISSUE TITLE
Extension frequently doesn't recognize existing edits

### ISSUE THREAD

**Issue by AquaDoesStuff** [web-scrobbler/web-scrobbler#3822] opened 2023-05-31 03:46 UTC
Title; I'm not sure if this is intentional, but it's annoying enough to where I decided I should probably write an issue about it. I listen to most of my music on Soundcloud, which often results in incorrect detected metadata by the extension, so I set it to only scrobble tracks I've saved edits for for it to automatically detect the edited metadata later and use on replays. However, even after the edit is saved, it often prompts that the track is unrecognized again, and forces me to edit it once more, completely ignoring the existing edit. If I view my saved edits, I can see that there is more than one edit saved per repeated tracks. Is there a way to fix this? Changing the mode doesn't seem to fix it either.

**Comment by yayuyokitano** [comment] 2023-05-31 03:52
This is probably a soundcloud connector issue with getting a unique ID for the song. This should not be happening. Thank you for reporting!

**Comment by inverse** [comment] 2023-05-31 11:27
Do you have a sample page which is problematic? I'm unable to reproduce this.

**Comment by AquaDoesStuff** [comment] 2023-06-03 05:18
it seems to be an issue based on playing a track on its own page vs in a playlist or an album, which I've already noticed already in soundcloud itself that if you're playing the track from an album it doesnt show that you're playing it on its page so I believe that may help with reproducing it if that's related to the issue.

**Comment by yayuyokitano** [comment] 2023-06-07 10:04
Makes sense. I would guess the URL being played from somehow affects the unique ID

**Comment by inverse** [comment] 2023-08-25 20:04
Resolved in #4050

**Closed by inverse** 2023-08-25 20:04 UTC
Labels: bug, connector
