### ISSUE TITLE
youtube does not scrobble

### ISSUE THREAD

**Issue by ilmailma** [web-scrobbler/web-scrobbler#2669] opened 2020-12-17 19:59 UTC
today during the day i noticed that i can't get the plugin to scrobble on youtube, no music was sent to last.fm. the plugin shows as if it is available on the page, but does not detect any music. would be great if you managed to find a way to fix it, please :) thanks!   ![image](https://user-images.githubusercontent.com/15608601/102536865-7c5cb300-40aa-11eb-9f81-e1558a16753b.png)

**Comment by inverse** [comment] 2020-12-17 20:11
@ilmailma could you provide more information.

- link to track that's failing to scrobble
- provide browser info
- debug logs (check wiki)

**Comment by Lubadubs** [comment] 2020-12-17 21:08
Hello,

I encountered the same issue so I thought I might help with the logs. I hope I made the logs correctly.

I am using Google Chrome version 87.0.4280.88.

"Works" for every song on YouTube (I tried some), but here the link to the one I used for the logs: https://www.youtube.com/watch?v=0XpSr9BSYr4

Debug log webscrobbler: https://pastebin.com/wPQEzXmH
Debug log website: https://pastebin.com/RpzBva7S

Thank you already in advance!

**Comment by alexesprit** [comment] 2020-12-18 06:21
Closed as a duplicate of #2667.

https://twitter.com/web_scrobbler/status/1339625550000885762?s=20

**Closed by alexesprit** 2020-12-18 06:21 UTC
