### ISSUE TITLE
Scrobble only first artist on YouTube Music

### ISSUE THREAD

**Issue by zhutra** [web-scrobbler/web-scrobbler#2725] opened 2021-02-02 13:59 UTC
I would like to request an option for YouTube Music to only scrobble the first artist that appears on the song. 
This can be achieved by splitting commas and leaving only the first value.
I always have to edit my YouTube Music tracks to remove commas, otherwise it scrobbles every single name as the track artist.

**Comment by alexesprit** [comment] 2021-02-02 14:23
Duplicate of #2588.

**Comment by alexesprit** [comment] 2021-02-02 14:24
> This can be achieved by splitting commas and leaving only the first value.

We cannot use this way - some artist names include comma symbol.

**Closed by alexesprit** 2021-02-02 14:23 UTC
Labels: duplicate

**Comment by zhutra** [comment] 2021-02-04 23:24
> > This can be achieved by splitting commas and leaving only the first value.
> 
> We cannot use this way - some artist names include comma symbol.

Yes, but when there's multiple artists the comma is followed by a space after.
Splitting ", " would be an easy/quick fix.

**Comment by alexesprit** [comment] 2021-02-05 05:56
> Also, another suggestion, is that you can extract every artist name individually from YT Music video descriptions, as they follow a template.

I know this (https://github.com/web-scrobbler/web-scrobbler/issues/2608#issuecomment-731719288).

**Comment by alexesprit** [comment] 2021-02-05 05:59
> Yes, but when there's multiple artists the comma is followed by a space after.

![image](https://user-images.githubusercontent.com/1119267/106995635-5c836a80-6790-11eb-82e5-a5310018cff6.png)
