### ISSUE TITLE
therock.nz

### ISSUE THREAD

**Issue by Jbenci** [web-scrobbler/web-scrobbler#2400] opened 2020-05-12 12:51 UTC
Im unable to scrobble music from https://www.therock.net.nz/home.player.html though it says its a supported website. Is there anything I can try?

**Comment by alexesprit** [comment] 2020-05-12 13:05
It says it's not supported for me (and this is expected). Could you post debug logs? 
[How to debug the extension.][1]

[1]: https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension

**Comment by Jbenci** [comment] 2020-05-12 13:13
Ive just realised there is more than one rockFM. I was attempting therock.net.nz which isnt actually supported. Perhaps a furture release can support it. Thanks and good day.

**Comment by alexesprit** [comment] 2020-05-12 13:20
Closed as a duplicate of #1931.

**Closed by alexesprit** 2020-05-12 13:20 UTC
Labels: duplicate
