### ISSUE TITLE
ListenOnRepeat: No recognition, no scrobbling

### ISSUE THREAD

**Issue by srgkoshelev** [web-scrobbler/web-scrobbler#1564] opened 2018-01-26 17:35 UTC
The design for ListenOnRepeat has changed. At this moment, the addon doesn't recognize or scrobble tracks.

### Expected behavior

Song that is played is recognized and scrobbled to Last.fm

### Current behavior

None of the songs played are recognized. When switching between songs no attempts to recognize are made (I guess the addon doesn't notice the switch). Refreshing the page forces an (unsuccessful) attempt of recognition.
If set manually, all songs are recognized as the the song that was set manually and NO scrobbling happens anyway.

NO issues on other websites, including same music directly from YouTube.

### Steps to reproduce (for bugs)

1. Go to http://listenonrepeat.com
2. Start any song
3. ???
4. PROFIT!

### Steps for resolving the issue

- [ ] Reauthenticate on Last.fm

- [ ] Try to use unpacked extension from latest master

- [ ] Check other issues for duplicates

### Environment

* Version used: 2.3.5
* Browser name and version: FF 58.0

**Comment by alexesprit** [comment] 2018-02-11 17:40
Closed as a duplicate of #1563.

**Comment by srgkoshelev** [comment] 2018-02-11 18:16
I am not sure what [listen.moe](https://listen.moe/) is but it seems to be distinctly different from [listenonrepeat](https://listenonrepeat.com/) that doesn't work still. Could you please look into it?

**Comment by alexesprit** [comment] 2018-02-11 18:26
Oh, sorry, I read the issue title non-properly. Thanks for pointing me on this!

**Comment by srgkoshelev** [comment] 2018-02-11 18:37
No worries! Thank you for doing such a great job with this addon!

**Closed** 2018-02-12 17:06 UTC
Labels: bug, connector
