### ISSUE TITLE
Youtube.com not being read

### ISSUE THREAD

**Issue by stelle-bts** [web-scrobbler/web-scrobbler#2668] opened 2020-12-17 12:00 UTC
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**Debug logs**
It's strongly recommended to grab [debug logs](https://github.com/web-scrobbler/web-scrobbler/wiki/Debug-the-extension) after reproducing the issue.

**Environment (please complete the following information)**
-   OS: (e.g. Windows, Mac)
-   Browser: (e.g. Chrome, Safari)
-   Extension version: (e.g. v2.10.0)

**Additional context**

**Comment by alexesprit** [comment] 2020-12-17 14:08
Closed as a duplicate of #2667.

**Closed by alexesprit** 2020-12-17 14:08 UTC
Labels: duplicate
